### ISSUE TITLE
Work of interest in mono-fork of IKVM.

### ISSUE THREAD

**Issue by ams-tschoening** [ikvm-revived/ikvm#10]
There has recently been some work which might be of interest here as well in the mono-fork of IKVM:

https://github.com/mono/ikvm-fork/commit/caa8e7f54279a47422626005d228447f5d3670d5
https://github.com/mono/ikvm-fork/commit/e9946684f05a4415e370c0298560c09d3c3a6973
https://github.com/mono/ikvm-fork/commit/9f805dcf8a87f46c0c5ef01e8468e92af2c2ef47

While the fork wasn't too active for some time and seems to be a heavy [stripped down version](https://github.com/mono/ikvm-fork/commit/00252c18fc0a4a206e45461736a890acb785a9d8) of IKVM, it might be a good idea to have an eye on new commits:

https://github.com/mono/ikvm-fork/commits/master

**Comment by tr33s** [comment]
I think this may be worth looking into in the future, because as of now Mono is the only way to achieve full AoT with .net.

**Comment by wasabii** [comment]
Stale.
