### ISSUE TITLE
IkvmReference ignores FileVersion (and AssemblyFileVersion)

### ISSUE THREAD

**Issue by NightOwl888** [ikvm-revived/ikvm#101]
When generating an assembly based off of a .jar file, it ignores the version number and outputs the assembly. I attempted to use `AssemblyFileVersion` and `FileVersion`, but neither works.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <IkvmReference Include="objenesis-3.2.jar" AssemblyName="objenesis">
      <AssemblyFileVersion>3.3.0.0</AssemblyFileVersion>
    </IkvmReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.0" />
  </ItemGroup>
</Project>
```

Note: To be [consistent with MSBuild, we should be using `FileVersion`](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#assembly-attribute-properties) rather than `AssemblyFileVersion` for this property.

**Comment by wasabii** [comment]
This feature was added after 8.2.0.

**Comment by wasabii** [comment]
I think this isn't a problem, since you were testing it in 8.2.0. If not the case, please reopen.

**Comment by viceice** [comment]
I see the same issue

https://github.com/visualon/featureide.net/pull/39/files
