### ISSUE TITLE
Cannot invoke main() method using Java Reflection

### ISSUE THREAD

**Issue by NightOwl888** [ikvm-revived/ikvm#107]
This uses the same setup as #80, but this is a completely different issue.

```c#
var jars = new List<URL>();

foreach (var file in System.IO.Directory.GetFiles(@"F:\maven-ikvm\maven", "*.jar", System.IO.SearchOption.AllDirectories))
{
	jars.Add(new File(file).toURI().toURL());
}

var cl = new URLClassLoader(jars.ToArray(), ClassLoader.getSystemClassLoader());

//java.lang.Thread.currentThread().setContextClassLoader(cl);

var classToLoad = Class.forName("org.codehaus.plexus.classworlds.launcher.Launcher", true, cl);

java.lang.System.setProperty("classworlds.conf", @"F:\maven-ikvm\maven\bin\m2.conf");
java.lang.System.setProperty("maven.home", @"F:\maven-ikvm\maven");
java.lang.System.setProperty("library.jansi.path", @"F:\maven-ikvm\maven\lib\jansi-native");
java.lang.System.setProperty("maven.multiModuleProjectDirectory", @"F:\maven-ikvm");

var mainMethod = classToLoad.getMethod("main", new java.lang.Class[] { typeof(string[]) });
mainMethod.invoke(null, new string[] {"org.apache.maven.plugins:maven-dependency-plugin:3.3.0:copy-dependencies",
		@"-DoutputDirectory=.\lib",
		"-DincludeScope=compile" });
```

Basically, the method accepts an array of `java.lang.String`. I can get aa reference to the method by using `typeof(string[])`. However, calling the method results in an error.

```console
java.lang.IllegalArgumentException
  HResult=0x80131500
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    Java_sun_reflect_ReflectionFactory.FastMethodAccessorImpl.invoke(object, object[], ikvm.internal.CallerID)
    java.lang.reflect.Method.invoke(object, object[], ikvm.internal.CallerID)
    java.lang.reflect.Method.invoke(object, object[])
    ConsoleApp69.Program.Main(string[]) in Program.cs
```

I cannot instantiate an array of `java.lang.String` because it is static, so I am unable to even try passing an array of them to `.invoke()`. 

I have been working around the issue by using .NET Reflection, which seems to be the only thing that works currently.

**Comment by wasabii** [comment]
`mainMethod.invoke(null, new string[] {"org.apache.maven.plugins:maven-dependency-plugin:3.3.0:copy-dependencies",`

`java.lang.reflect.Method` accepts two parameters. The first is the instance of the object to invoke the method on. The second is an array of objects to pass as arguments to the method.

The `main` method you are invoking accepts a single argument: an array of strings.

You are attempting to invoke it by passing three arguments of type string.

And as such it is throwing an IllegalArgumentException.
