### ISSUE TITLE
Is https://github.com/jessielesbian/ikvm a fork of interest?

### ISSUE THREAD

**Issue by ams-tschoening** [ikvm-revived/ikvm#11]
That fork has been mentioned on [some wwrd-issue](https://github.com/wwrd/ikvm8/issues/10#issuecomment-588291035) and seems pretty active the last few months. The problem I see is with the following commit changing the license of the project:

https://github.com/jessielesbian/ikvm/commit/3d905b08f0adf6c1493ea7c468c8eaa898b2b242

Is that even legal, removing the former license and copyright holders, most likely without their permissions?

> 3. This notice may not be removed or altered from any source distribution.

**Comment by 0xF6** [comment]
Hmm, there is to take into account the previous license which describes the copyrights of all authors, including Oracle - it is not legal to delete the code of the old license without written permission.

**Comment by ams-tschoening** [comment]
So let's simply come to the conclusion that this fork is NOT of interest because of the licensing issues.

**Comment by ams-tschoening** [comment]
Just for reference, the licence changes has been discussed in the mentioned repos as well:

https://github.com/jessielesbian/ikvm/issues/3
https://github.com/jessielesbian/ikvm/issues/18
