### ISSUE TITLE
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: sun/nio/ch/Net.isExclusiveBindAvailable()

### ISSUE THREAD

**Issue by jvmx** [ikvm-revived/ikvm#113]
I ran into the following error when trying to use a .dll in .NET5 and .NET6 on a Windows 2019 machine. Any idea how to fix this?

I know active work is being done on "linux sockets" -- is that work that solves this issue? I'm a bit unclear if that's what you mean by "linux sockets" even though this is a Windows 2019 machine. I also saw some reference to "nio sockets" and since nio appears in this error message I'm wondering if that's what people are referring to as well.

> Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: sun/nio/ch/Net.isExclusiveBindAvailable()I
>         at cli.IKVM.Runtime.JNI$Frame.GetFuncPtr(Unknown Source)
>         at sun.nio.ch.Net.isExclusiveBindAvailable(Native Method)
>         at sun.nio.ch.Net.<clinit>(Net.java:54)
>         at sun.nio.ch.Net.socket(Net.java:409)
>         at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:105)
>         at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60)
>         at java.nio.channels.SocketChannel.open(SocketChannel.java:145)
>         at [REDACTED].Client$SessionThread.run(Unknown Source)

**Comment by wasabii** [comment]
Looks like an error with a moved JNI-like function signature. Fixed on develop.

**Comment by jvmx** [comment]
This error is not fixed in the 8.2.1 build available for download, correct? Still get same error in that build.

**Comment by jvmx** [comment]
> Looks like an error with a moved JNI-like function signature. Fixed on develop.

This error is not fixed in the 8.2.1 build available for download, correct? Still get same error in that build.

**Comment by wasabii** [comment]
It should be fixed there yes.
