### ISSUE TITLE
IKVM.NET.Sdk

### ISSUE THREAD

**Issue by wasabii** [ikvm-revived/ikvm#118]
Proposal for a new `IKVM.NET.Sdk` package that allows one to build Java projects, with .java source code.

Users Would add a `<Project Sdk="IKVM.NET.Sdk" >...</>` tag onto their `msbuildproj` files to opt in.

Sdk would be modeled after Microsoft.NET.Sdk, and likely inherit from it. Support multiple language, Java being the primary one (Kotlin anybody, woh!)

Would use standard MSBuild ItemGroups: `Compile` would point to .java files.

Compiler could be implemented in IKVM itself (javax.tools).

SDK would be used to replace the build logic in IKVM.Java itself in a bootstrap mode.

Eventual Language Service. Could make use of ECJ.

Eventual VSIX (or whatever they're calling them now) with a .ikvmproj extension or some such.

**Comment by wasabii** [comment]
I'm working on this now in order to implement IKVM.JavaTest in the project, as that project has required me to actually import the JTReg source code and make changes.

**Comment by GeorgeS2019** [comment]
[This: KVM.NET.Sdk](https://github.com/ikvm-revived/ikvm/pull/122) is super exciting

**Comment by wasabii** [comment]
This issue is the discussion. That nobody else participates is unfortunate.

**Comment by GeorgeS2019** [comment]
@wasabii  

Have you considered updating[ IKVM wiki?](https://en.wikipedia.org/wiki/IKVM.NET)  .NET6 is disruptive after ~9 years

**Comment by wasabii** [comment]
IKVM.NET.Sdk has been mostly finalized. Hopefully I can get it in today.

One thing to note is that it will only support TFMs of net461 and netcoreapp3.1, with the former only buildable on Windows. The first part of this should be fine, since building netcoreapp3.1 projects doesn't preclude them from being consumed in higher platforms. The former is a continuation of the requirement that only the Framework tools build Framework assemblies. And Framework tools won't run on Linux.

**Comment by GeorgeS2019** [comment]
Incredible!

**Comment by NightOwl888** [comment]
> Framework tools won't run on Linux.

@wasabii - I have several projects setup to build .NET Framework DLLs on Linux, and I have confirmed it works. The .NET SDK builds .NET Framework on Linux, but there is no way to run the tests on Linux.

For example: https://github.com/Spatial4n/Spatial4n/blob/main/docs/building-and-testing.md#linux-or-macos builds both .NET Framework 3.5 and .NET Framework 4.0 assemblies on Linux and packages them into a `.nupkg` file, but skips the tests for .NET Framework when running on Linux.

Is there something in IKVM that is laborious that is preventing us from building .NET Framework on Linux, or was this just based on an invalid assumption?

**Comment by wasabii** [comment]
Yes. The IKVMC tool is pretty nasty for a use case like this.

ikvmc as I see it was kind of an addon. The main portion of IKVM is the runtime, for finding, loading, compiling, dynamic assemblies from the ClassLoader set. The static compiler (ikvmc) imports a bunch of types from the main part of IKVM, and expects them to sort of work at runtime. It fires up the classloaders, it fires up the JVM. It then takes the code path that would otherwise generate dynamic assemblies, and runs it by hand on the loaded wrappers, emitting a static assembly instead.

The problem is a lot of the type names loaded by the JVM and Universe classes are used to generate the final assembly. As they would be at runtime. Except, they differ between Framework and Core. For instance, something as simple as System.Object. On Framework, it's in mscorlib. On Core it's in System.Runtime.

The problem is when you launch the ikvmc app compiled to core, the `object` type is System.Runtime. Except it'll need to emit an assembly targeting mscorlib.

What needs to happen here is to break the hard dependency between the current runtime and the assemblies being built. No longer depending on things like typeof(object), etc. But load them all from the set of references passed in at runtime. Which is another issue on the various platforms: assemblies on Core can only be loaded once per name in an AssemblyContext. So you can't simultaniously load System.Runtime from coreapp3.1, and System.Runtime from net5, for instance. Same assembly name.

What needs to happen is what happened ultimately in Roslyn. System.Reflection.Metadata was devised to allow one to parse assemblies, look at metadata, and build assemblies, without relying on System.Type at all, or any local runtime information.
