### ISSUE TITLE
And where are the executable - ikvmc.exe and so on?

### ISSUE THREAD

**Issue by jayjupdhig** [ikvm-revived/ikvm#121]
Can't find them in 

https://github.com/ikvm-revived/ikvm/releases/download/8.2.1/IKVM-8.2.1-bin-net461.zip

https://github.com/ikvm-revived/ikvm/releases/download/8.2.1/IKVM-8.2.1-bin-netcoreapp3.1.zip

why?

thx for feedback.

**Comment by jayjupdhig** [comment]
And which java version does it support? Higher than 1.7 ?

**Comment by jayjupdhig** [comment]
Now ive found zip with .exe but it does not work:


Buildfile: D:\Development\IDE\jee-2022-06\eclipse\workspace\MosquittoUsrAcctGen\ant\build.xml
create_run_jar:
      [jar] Building jar: D:\Development\IDE\jee-2022-06\eclipse\workspace\MosquittoUsrAcctGen\build\MosquittoUsrAcctGen.jar
    [unzip] Expanding: D:\Development\IDE\jee-2022-06\eclipse\workspace\MosquittoUsrAcctGen\build\MosquittoUsrAcctGen.jar into C:\Windows\Temp\MosquittoUsrAcctGen
   [delete] Deleting: D:\Development\IDE\jee-2022-06\eclipse\workspace\MosquittoUsrAcctGen\build\MosquittoUsrAcctGen.jar
   [delete] Deleting directory C:\Windows\Temp\MosquittoUsrAcctGen\junit
   [delete] Deleting directory C:\Windows\Temp\MosquittoUsrAcctGen\org
   [delete] Deleting directory C:\Windows\Temp\MosquittoUsrAcctGen\com\xaxada\tools\mosquitto\testing\junit
      [zip] Building zip: D:\Development\IDE\jee-2022-06\eclipse\workspace\MosquittoUsrAcctGen\build\MosquittoUsrAcctGen.jar
   [delete] Deleting directory C:\Windows\Temp\MosquittoUsrAcctGen
     [exec] IKVM.NET Compiler (8.2.1+Branch.main.Sha.e85684966cf595d7942d6930fda9c27d23b509e1)
     [exec] Copyright � 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug
     [exec] note IKVMC0004: Using main class "com.xaxada.tools.mosquitto.testing.MosquittoUsrAcctGenTest" based on jar manifest
     [exec] *** INTERNAL COMPILER ERROR ***
     [exec] PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE
     [exec] ikvmc, Version=8.2.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
     [exec] D:\Tools\IKVM\IKVM-8.2.1-tools-ikvmc-netcoreapp3.1\win7-x64\
     [exec] 3.1.27 64-bit
     [exec] System.IO.FileNotFoundException: netstandard
     [exec]    at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\a\ikvm\ikvm\src\IKVM.Reflection\Universe.cs:line 789
     [exec]    at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in D:\a\ikvm\ikvm\src\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
     [exec]    at ikvmc.IkvmcCompiler.Compile(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 178
     [exec]    at ikvmc.IkvmcCompiler.Main(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 112
     [exec] Result: 2
BUILD SUCCESSFUL
Total time: 1 second

**Comment by jayjupdhig** [comment]
Neither with java 1.7 nor with most current java 17...

**Comment by wasabii** [comment]
Well that's was a ride.

**Comment by jayjupdhig** [comment]
...so we need to go back to Java 1.7. with https://github.com/jessielesbian/ikvm. But that's OK.

**Comment by ams-tschoening** [comment]
Just in case you didn't recognize yet, that fork has licensing issues most likely:

https://github.com/jessielesbian/ikvm/issues/3
https://github.com/jessielesbian/ikvm/issues/18
https://github.com/ikvm-revived/ikvm/issues/11

**Comment by jayjupdhig** [comment]
thank you for your feedback.
