### ISSUE TITLE
IKVM.NET.Sdk sample

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvm-revived/ikvm#123]
It would be great to have a repo that provides ready-to-go example that shows how IKVM.NET.SDK works.

**Comment by GeorgeS2019** [comment]
IKVM.Maven
https://github.com/martin-honnen/CoffeeSacksIKVMTest4

**Comment by wasabii** [comment]
You mean IKVM.maven.sdk?

There's only a package reference that needs to be added. And it's documented in the readme. So I'm not sure of what use this would be.
