### ISSUE TITLE
fatal error IKVMC5025: Unable to load runtime assembly

### ISSUE THREAD

**Issue by sergey-tihon** [ikvm-revived/ikvm#126]
What is wrong with this IKVMC call?

`
x:\OpenNLP.NET\bin\lib\net461> "x:\OpenNLP.NET\paket-files\github.com\any\ikvmc.exe"  -out:grizzly-framework-2.4.4.dll -version:2.4.4 "x:\OpenNLP.NET\paket-files/dlcdn.apache.org/apache-opennlp-2.0.0/lib\grizzly-framework-2.4.4.jar"
`

I do compile `grizzly-framework-2.4.4.jar` using  `any\ikvmc.exe` downloaded from https://github.com/ikvm-revived/ikvm/releases/download/8.2.1/IKVM-8.2.1-tools-ikvmc-net461.zip on Windows.

and receive output

```
IKVM.NET Compiler (8.2.1+Branch.main.Sha.e85684966cf595d7942d6930fda9c27d23b509e1)
Copyright © 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

fatal error IKVMC5025: Unable to load runtime assembly
```

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/1197905/185999354-23c0e00c-f673-4ff5-bc4e-80c8bf8f6d33.png">

**Comment by wasabii** [comment]
Need to specify -runtime pointing to IKVM.Runtime.

**Comment by wasabii** [comment]
Nope. That's the goal, but it's not the current state. Right now net461 can only compile targeting net461, and netcoreapp3.1 can only target netcoreapp3.1.

**Comment by wasabii** [comment]
The IKVM NuGet package provides MSBuild support for all of this, working out the details. You can add a `<IkvmReference>` pointing to the JAR files, and it'll run the right thing.

**Comment by wasabii** [comment]
Like, you should be able to use OpenNLP by just adding two lines to your MSBuild file today:
```
<PackageReference Include="IKVM" Version="8.2.0" />
<MavenReference Include="org.apache.opennlp:opennlp-tools" Version="2.0.0" />
```

**Comment by sergey-tihon** [comment]
Thank you, I think that this particular issue is resolved.

**Comment by sergey-tihon** [comment]
@wasabii fyi, confirm that MavenReference actually works for `opennlp-tools` `1.9.4` 

https://github.com/sergey-tihon/OpenNLP.NET/pull/18

**Comment by wasabii** [comment]
Neat. Long road to JDK9+ unfortunately.
