### ISSUE TITLE
Support for Java 11+?

### ISSUE THREAD

**Issue by jpgpng** [ikvm-revived/ikvm#133]
The latest LTS is already Java 17 and there is so many changes but you are only started mentioned JDK 9 a few days ago (https://github.com/ikvm-revived/ikvm/issues/120). JDK 9 is not LTS and is already EOL. Please support Java 11+ (if it could be Java 17+ then it's much better). Thanks.

**Comment by wasabii** [comment]
Kinda got to do 9 first.

**Comment by jpgpng** [comment]
> Kinda got to do 9 first.

Implement JEPs incrementally from Java 9 and finally will be Java 11+ (or better Java 17+)? I use some Java 11+ apps and I could test them on ikvm and report bugs.

**Comment by wasabii** [comment]
Closing. JDK 9 has to come first.
