### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jpgpng** [ikvm-revived/ikvm#135]
On release page there is so many zips. I downloaded them all but have no idea how to use. What is the different between them? Which I really need and how to set them up?

`IKVM-8.2.2-prerelease.163-bin-net461.zip`
`IKVM-8.2.2-prerelease.163-tools-ikvmc-net461.zip`
`IKVM-8.2.2-prerelease.163-tools-ikvm-net461.zip`
`IKVM-8.2.2-prerelease.163-tools-ikvmstub-net461.zip`

I tried to run Pixelitor. First with ikvmc to compile it to a .NET exe. ikvmc said it can't find libraries bla bla... So I merge the content of `IKVM-8.2.2-prerelease.163-bin-net461.zip` and `IKVM-8.2.2-prerelease.163-tools-ikvmc-net461.zip\any` and now I could have it compiled. But it doesn't run, it said it can't find library awt Tooling or something like that. Pixelitor is a Java Swing app. I remember ikvm could run Java gui application, right? Why it doesn't work?

Then I merged the content of all of these zips into one folder, move anything under the `any` directory to the root directory. I tried to run the jar directly via ikvm -jar but it still fails with the same error.

Note: latest Pixelitor requires Java 17+, so I tried with previous versions from 4.2.3 to even 4.2.0, none of them worked. It remember 4.2.0 supports Java 8. So this must be something wrong with ikvm itself. BTW, why there are absolutely no documents? At least tell me which purposes each of the zips serve and how to set them up to run jars. Thanks.

**Comment by jpgpng** [comment]
Here is Pixelitor: https://sourceforge.net/projects/pixelitor/files/

**Comment by wasabii** [comment]
IKVM does not support AWT.
