### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by asbjornu** [ikvm-revived/ikvm#139]
Thanks for publishing version 8.2.1 of IKVM! I'm trying to give it a spin on Ubuntu 22.04, and seem to be stuck with the following error message when executing `ikvmc`:

```
No usable version of libssl was found
Aborted (core dumped)
```

I've installed `libssl-dev` version `3.0.2-0ubuntu1.6` and wonder which version of libssl I need or if there's anything else I have to do in order to get `ikvmc` to work under Ubuntu 22.04.

**Comment by asbjornu** [comment]
I don't seem to be getting this in Ubuntu 20.04, which has version `1.1.1f-1ubuntu2.16` of `libssl-dev` installed.

**Comment by wasabii** [comment]
Well it's going to be whatever version dot net core 3.1 requires. And it's not going to be -dev packages.

**Comment by asbjornu** [comment]
Yeah, seems like version 1 is required, since I don't get any such errors on Ubuntu 20.04 (which comes with version `1.1.1f-1ubuntu2.16`), @wasabii.
