### ISSUE TITLE
ikvmstub

### ISSUE THREAD

**Issue by asbjornu** [ikvm-revived/ikvm#140]
I can see from #125 that `ikvmstub` has been renamed to `IKVM.Tool.Exporter`, but I'm unable to find anything named `IKVM.Tool.Exporter` or `ikvmstub` in the [IKVM package](https://www.nuget.org/packages/IKVM) after installation (`dotnet restore`). Where do I find the executable formerly known as `ikvmstub`? :)

For a bit of context, I'm working on https://github.com/HtmlUnit/NHtmlUnit/pull/36 where I'm currently trying to translate the old [`make.cmd` script](https://github.com/HtmlUnit/NHtmlUnit/blob/fca85b0db564a0b75093f4e36dbb54109c62e5fe/lib/HtmlUnit/Make.cmd) into whatever version 8.2.1 of IKVM supports. I'm currently stuck at [the following line](https://github.com/HtmlUnit/NHtmlUnit/blob/fca85b0db564a0b75093f4e36dbb54109c62e5fe/lib/HtmlUnit/Make.cmd#L21):

```cmd
%IKVMSTUB% mscorlib
```

So what I'm really wondering is how do I stub `mscorlib` with version 8.2.1 of IKVM? If it is still with the `ikvmstub` executable, I need to know where I can find it.

Thanks!

**Comment by wasabii** [comment]
It's in the tools artifact.

Looking over htmlunit, however, this is a project which would be using IKVM.Maven.Sdk

**Comment by asbjornu** [comment]
> It's in the tools artifact.

Okay, how do I find the executable after having done `dotnet restore`? Where is the tools artifact placed after package installation?

> Looking over htmlunit, however, this is a project which should be using IKVM.Maven.Sdk

Thanks for the tip, I'll look into it! 👍🏼

**Comment by asbjornu** [comment]
From the looks of it, `IKVM.Maven.Sdk` can possibly be used by .NET applications that want to reference the Java-based HtmlUnit directly, circumventing NHtmlUnit and alleviating its need to exist, entirely. Is that what you are suggesting? If so, that's definitely an interesting approach.

**Comment by wasabii** [comment]
Of they don't want to use your wrappers, sure . But your wrappers can still exist in nuget.

**Comment by wasabii** [comment]
The tools artifact is an artifact. On the github releases page.

**Comment by asbjornu** [comment]
OKay, cool. Found it. However, when executing `ikvmstub mscorlib` I get the following error:

```cs
Unhandled exception. System.IO.FileNotFoundException: netstandard
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\a\ikvm\ikvm\src\IKVM.Reflection\Universe.cs:line 789
   at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in D:\a\ikvm\ikvm\src\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
   at ikvmstub.Program.Main(String[] args) in D:\a\ikvm\ikvm\src\ikvmstub\ikvmstub.cs:line 161
Aborted (core dumped)
```

**Comment by wasabii** [comment]
Primary issue was answered. If new one open new issue.
