### ISSUE TITLE
.NET 6 Arm iOS support

### ISSUE THREAD

**Issue by kevincrans** [ikvm-revived/ikvm#143]
This way people will finally be able to port java apps to iOS.
Lwjgl 3~ already supports arm and moltenVK, but not both at the same time.

**Comment by wasabii** [comment]
Most of IKVM will probably work fine on any Core runtime regardless of platform. The only exceptions are JNI.

**Comment by kevincrans** [comment]
@wasabii Thank you, but it clearly says core 3.1 and not .net 5 or 6, so is arm supported at all?

**Comment by wasabii** [comment]
It is as I said.

**Comment by kevincrans** [comment]
Yeah, thank u, I read .net 5 on the page and wonder why I asked (probably looked at something old)

**Comment by wasabii** [comment]
The exception are the compiled tools, which are available for net461 and netcoreapp3.1, win7-x64 and linux-x64. But those are just the tools. The actual runtime is a pure .NET assembly. Except for the JNI component.
