### ISSUE TITLE
Internal Compiler Error for ikvmc (pre-compiled)

### ISSUE THREAD

**Issue by jwoff78** [ikvm-revived/ikvm#145]
https://hastebin.com/tefamisimu.less
The link above show's the error so this message doesn't get over crowded, I've noticed someone else with same issue where the compiler was trying to access "D:\a\ikvm\..." and it wasn't found, along with that the original error is FileNotFoundException "netstandard"

If anyone can provide support I'd appreciate it.

**Comment by wasabii** [comment]
Duplicate of #142
