### ISSUE TITLE
ikvmdoc

### ISSUE THREAD

**Issue by MattLichter** [ikvm-revived/ikvm#15]
First, thanks for keeping this project alive!  It's an incredible tool and I'm grateful to see all the recent work to coalesce the various forks.

Does anyone here have any experience using IKVMDoc?  I'd like to generate XML intellisense files from javadoc.  I already have the following files:
- Input library
  - libfoo.jar
  - libfoo-sources.jar
  - libfoo-javadoc.jar
- Output library (successfully generated by IKVMC)
  - libfoo.dll
  - libfoo.pdb

Now I just want to use IKVMDoc to generate libfoo.xml.  Does anyone happen to know the process/commands to do this?

**Comment by ams-tschoening** [comment]
Do you have a binary already and asking how to invoke it or need the binary as well or ...? I'm not aware of any specific docs, but looking at the [source file](https://github.com/ikvm-revived/ikvm/blob/master/ikvmdoc/IKVMDoc.java), things should be compatible to javadoc:

    usage: ikvmdoc [options] [packagenames] [sourcefiles] [@files]

A binary can be built by simply running "nant" in the ikvmdoc-directory:

    set PATH=%PATH%;C:\Program Files (x86)\NAnt\bin
    set PATH=%PATH%;C:\Program Files\Java\jdk-8\bin
    nant

[ikvmdoc.exe.txt](https://github.com/ikvm-revived/ikvm/files/4263334/ikvmdoc.exe.txt)

Invoking the following way works, but runs into errors:

	C:\Users\[...]\ikvm\bin>ikvmdoc "..\ikvmdoc\IKVMDoc.java"
	Loading source file ..\ikvmdoc\IKVMDoc.java...
	Constructing Javadoc information...
	..\ikvmdoc\IKVMDoc.java:21: error: package com.sun.javadoc does not exist
	import com.sun.javadoc.*;
	^
	[...]
	ikvmdoc: error - In doclet class IKVMDoc,  method start has thrown an exception java.lang.reflect.InvocationTargetException
	java.lang.NullPointerException
	        at IKVMDoc.start(IKVMDoc.java:165)
	        at java.lang.reflect.Method.invoke(Method.java:486)
	        at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:309)
	        at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
	        at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
	        at com.sun.tools.javadoc.Start.begin(Start.java:219)
	        at com.sun.tools.javadoc.Start.begin(Start.java:205)
	        at com.sun.tools.javadoc.Main.execute(Main.java:120)
	        at IKVMDoc.main(IKVMDoc.java:783)
	1 error
	19 warnings

**Comment by MattLichter** [comment]
@ams-tschoening Thanks!  That's a big step in the right direction.  I tried running your exe but it references newer versions of the IKVM binaries, so I'll take a step back and run NAnt as you suggest.  I would not have known to do that.  I'll keep you posted...

**Comment by MattLichter** [comment]
@ams-tschoening I was able to rebuild ikvmdoc.exe with NAnt, just like you suggested.  Thanks!

However, when I run the app I end up with exactly the same errors that you show above.  I spent a while trying a lot of command line options, using the built-in help as well as [help docs for the javadoc app](https://docs.oracle.com/javase/9/javadoc/javadoc-command.htm#JSJAV-GUID-EAAAE17F-E540-42A0-B22B-4D2B2FD3E4D2) this was apparently modeled after.  I guess I'm in over my head on this topic.

I guess I'll leave this issue open for now in case anyone else has first-hand experience with the tool.

**Comment by MattLichter** [comment]
Ok took a fresh look and I think I may have gotten the syntax right finally

```
.\ikvmdoc.exe -assembly .\libfoo.dll -sourcepath .\libfoo-sources -subpackages org.foo
```
where `libfoo.dll` is the output of `ikvmc.exe`, and `libfoo-sources` is the unzipped contents of `libfoo-sources.jar`.  The assembly option was the key to eliminating the last exception (IKVMDoc.java:165).

I'll do a bit more tinkering tomorrow and make sure I can reproduce this on my work machine before closing.  @ams-tschoening thanks again for the NAnt and PATH hint in your last reply!

**Comment by ams-tschoening** [comment]
Good news and 2 suggestions:

IKVMDoc doesn't seem to be part of the [default build](https://github.com/ikvm-revived/ikvm/blob/master/ikvm.build#L35) currently. How about adding it? That way it could be added to the [bin-repo](https://github.com/ams-ts-ikvm/ikvm-bin) as well and would be available to people like you by default.

How about adding a small `README.md` containing what you have found so far? That would make it easier for people to start without looking at source code. Simply add one to the [already available directory](https://github.com/ikvm-revived/ikvm/tree/master/ikvmdoc) would be enough to start with.

**Comment by MattLichter** [comment]
@ams-tschoening Yes let me look into that.  I already tried doing the obvious, adding to the root build but there were some pathing issues I needed to sort out and I still ended up with a few errors.  I've never used NAnt so I may need to study up a bit.  But if I get things ironed out, I will do as you suggest.

**Comment by ams-tschoening** [comment]
I've attached a patch in the meantime that should solve your path-related problems. Apply that, create README.md, test things and provide a PR for review. Shouldn't be too much work anymore.

https://github.com/ikvm-revived/ikvm/files/4266067/build_ikvmdoc_by_default.patch.txt

**Comment by wasabii** [comment]
Stale.
