### ISSUE TITLE
IkvmReference donot work in Visual Studio2022

### ISSUE THREAD

**Issue by xiaochao00** [ikvm-revived/ikvm#150]
When I use ikvm in Visual Studio2022, and add the config by hand:
```
<ItemGroup>
    <PackageReference Include="IKVM" Version="8.2.0" />
  </ItemGroup>
  <ItemGroup>
    <IkvmReference Include="ext\helloworld-2.0.jar" />
  </ItemGroup>
```
The steps I used this is

1. create CTL by VS named nuget_demo;
2. modify nuget_demo.csproj, and add the ikvm and jar config;
3. then success build in VS, but I can`t find helloworld.dll;

Is if any way I was wrong in used?
my project structure is :
![image](https://user-images.githubusercontent.com/16160841/190344769-e5db67ca-fbfa-4b11-a9f6-7946a624e502.png)

**Comment by GeorgeS2019** [comment]
This is still the best documentation so far: I[KVM.NET.Sdk sample](https://github.com/ikvm-revived/ikvm/issues/123)

**Comment by xiaochao00** [comment]
Thanks [GeorgeS2019](https://github.com/GeorgeS2019) , I was success by modified config by hand too, but it could not work by auto-generate by VS; So I gave up using VS.
