### ISSUE TITLE
win7-x64?

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvm-revived/ikvm#161]
win7-x64? Something from the old past?
`ikvm\src\ikvmstub\bin\Debug\netcoreapp3.1\win7-x64\publish\ikvmstub.exe`

**Comment by NightOwl888** [comment]
Nope, [RID](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#windows-rids) is how .NET Core versions are identified when compiling them for specific runtimes.

> **NOTE:** It is possible to produce a [cross-platform binary](https://learn.microsoft.com/en-us/dotnet/core/deploying/#produce-a-cross-platform-binary), but not sure whether that is something that has been looked into for the IKVM tools.

**Comment by wasabii** [comment]
If the question is just..... why is there a win7-x64 published executable, I guess that's been answered?
