### ISSUE TITLE
IkvmReference from Jar file

### ISSUE THREAD

**Issue by hrfmartins** [ikvm-revived/ikvm#168]
When importing a Jar file as `IKVMReference`, there are several issues showing up.

### Reproducible example:

![MinExample](https://user-images.githubusercontent.com/32126871/192137453-155f0a67-965a-4595-8faf-c154e0e3e954.png)
 
Just a simple class, with two static methods. The package name is `pt.example.hm`. Here is the example: https://github.com/hrfmartins/JavaExample

The output Jar can be found in the out/artifacts/SimpleAppTest.jar

### The issues

After adding the jar file to the application and importing it with:
```
<ItemGroup>
    <IkvmReference   Include="libs\SimpleAppTest.jar">
    </IkvmReference>
  </ItemGroup>
```

I get some errors. Firstly, when building the assembly, I get two errors:

- `Error IKVMSDK0002 : The IkvmReference libs\SimpleAppTest.jar has invalid AssemblyName ''.`
- `Error IKVMSDK0003 : The IkvmReference libs\SimpleAppTest.jar has invalid AssemblyVersion ''.`

After reading the documentation, I tried adding them, but I get a warning: 
`Warning MSB3245 : Could not resolve this reference. Could not locate the assembly "SimpleAppTest, Version=1.0". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.`

**Comment by NightOwl888** [comment]
With 8.2.1 and `netcoreapp3.1`, I was able to reproduce the errors (although I also got an error for `AssemblyFileName`). However, after adding all 3 to `IkvmReference`, it simply fails silently.

While tinkering, I was able to get it to output the `SimpleAppTest.dll` below `obj/Debug/netcoreapp3.1/ikvm`, but I am not sure what caused it to happen or caused it to stop working afterward. It also didn't copy the file to the `bin` folder.

I then tried with 8.2.2-prerelease0553 and it works when the `AssemblyName` and `AssemblyVersion` attributes are specified.

```xml
  <ItemGroup>
    <IkvmReference   Include="SimpleAppTest.jar">
      <AssemblyName>SimpleAppTest</AssemblyName>
      <AssemblyVersion>1.0.0</AssemblyVersion>
    </IkvmReference>
  </ItemGroup>
```

To make it automatically derive the `AssemblyName` from the MANIFEST.MF file, you would need to [define the `Automatic-Module-Name`](https://github.com/ikvm-revived/ikvm#automatic-module-name-specification).

But the fact that it cannot derive the `AssemblyVersion` from `Manifest-Version` in the MANIFEST.MF file when `Automatic-Module-Name` is not defined seems like a bug.

> NOTE: If the above doesn't resolve the issue, it would be helpful if you would include instructions (or better yet, a script) for building the jar file so we can rule out differences in procedure for building the jar as a possible cause.

**Comment by wasabii** [comment]
Manifest-Verzion isn't the version of the assembly. It's the version of the manifest specification.

**Comment by NightOwl888** [comment]
@wasabii - Where is the AssemblyVersion derived from automatically? The jar file name?

**Comment by hrfmartins** [comment]
I think it is. I tried renaming the jar with the syntax *-version.jar and it was picked up, no more assembly-name or assembly-version requested

**Comment by hrfmartins** [comment]
I just managed to get it working on `8.2.2-prerelease0553`, I had to specify the `AssemblyName ` and `AssemblyVersion`, but I think I managed to get it working. I need to do some more testing though

**Comment by wasabii** [comment]
Yeah. It follows the automatic module name specification. If it can.

**Comment by wasabii** [comment]
Bug 100 fix might not have made it into 8.2.1, can't remember. If not, the version isn't normalized properly.

So it might have generated with 1.0.0.0, but you're trying to reference it with 1.0. which is different.

Set assembly name by hand to four components.

**Comment by hrfmartins** [comment]
After some testing, it seems that some methods still suffer from this bug

After testing with a generated Jar file from another program, some methods seem to be fine, while others seem to be affected, and they trigger the `Could not load file or assembly` error.

**Comment by wasabii** [comment]
As of now, different people have described a number of different problems on this thread. The first post talks about warnings from the MSBuild scripts. Both of these have had solutions offered, I believe.

I do not currently know what outstanding issues there are and have no way to reproduce or describe them.

**Comment by wasabii** [comment]
Stale
