### ISSUE TITLE
catch ClassNotFoundException does not work

### ISSUE THREAD

**Issue by kztao** [ikvm-revived/ikvm#171]
This  code doesn't work
`
`boolean reactorHttpClientPresent = false;
        try {
            Class.forName("reactor.netty.http.client.HttpClient", false, loader);
            reactorHttpClientPresent = true;
        } catch (ClassNotFoundException e) {
        }``

[https://github.com/flowable/flowable-engine/blob/main/modules/flowable-http-common/src/main/java/org/flowable/http/common/impl/HttpClientConfig.java](url)

dotnet run :
```
PS F:\Projects\flowable-demo\netcore> dotnet run
...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Unhandled exception. System.TypeInitializationException: The type initializer for 'org.flowable.engine.cfg.HttpClientConfig' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'org.flowable.http.common.impl.HttpClientConfig' threw an exception.
 ---> ClassNotFoundException: org.springframework.web.reactive.function.client.WebClient
   at IKVM.Java.Externs.java.lang.Class.forName0(String name, Boolean initialize, ClassLoader loader, Class caller)
   at java.lang.Class.forName0(String name, Boolean initialize, ClassLoader loader, Class caller)
   at java.lang.Class.forName(String name, Boolean initialize, ClassLoader loader, CallerID )
   at org.flowable.http.common.impl.HttpClientConfig..cctor()
   --- End of inner exception stack trace ---
   at org.flowable.http.common.impl.HttpClientConfig.__<clinit>()
   at org.flowable.engine.cfg.HttpClientConfig..cctor()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(RuntimeTypeHandle type)
   at IKVM.Internal.TypeWrapper.RunClassInit()
   at IKVM.Runtime.ByteCodeHelper.DynamicNewCheckOnly(Class clazz)
   at org.flowable.engine.ProcessEngineConfiguration..ctor()
   at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl..ctor()
   at org.flowable.engine.impl.cfg.StandaloneProcessEngineConfiguration..ctor()
   at Program.<Main>$(String[] args) in F:\Projects\flowable-demo\netcore\Program.cs:line 12```

**Comment by wasabii** [comment]
ClassNotFoundException: org.springframework.web.reactive.function.client.WebClient

Is that class available?

**Comment by wasabii** [comment]
I'm sorry, I have no idea from this post what you are trying to do, what JAR file you converted, how you converted it, etc.

**Comment by kztao** [comment]
.csproj:


<ItemGroup&gt;
&nbsp; &nbsp; <PackageReference Include="IKVM" Version="8.2.1" /&gt;
&nbsp; &nbsp; <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" /&gt;
&nbsp; </ItemGroup&gt;

&nbsp; <ItemGroup&gt;
&nbsp; &nbsp; <MavenReference Include="commons-logging:commons-logging"&gt;
&nbsp; &nbsp; &nbsp; <groupId&gt;commons-logging</groupId&gt;
&nbsp; &nbsp; &nbsp; <artifactId&gt;commons-logging</artifactId&gt;
&nbsp; &nbsp; &nbsp; <Version&gt;1.2</Version&gt;
&nbsp; &nbsp; </MavenReference&gt;
&nbsp; &nbsp; <MavenReference Include="org.flowable:flowable-engine"&gt;
&nbsp; &nbsp; &nbsp; <groupId&gt;org.flowable</groupId&gt;
&nbsp; &nbsp; &nbsp; <artifactId&gt;flowable-engine</artifactId&gt;
&nbsp; &nbsp; &nbsp; <version&gt;6.7.2</version&gt;
&nbsp; &nbsp; </MavenReference&gt;
&nbsp; &nbsp; <MavenReference Include="org.flowable:flowable-http"&gt;
&nbsp; &nbsp; &nbsp; <groupId&gt;org.flowable</groupId&gt;
&nbsp; &nbsp; &nbsp; <artifactId&gt;flowable-http</artifactId&gt;
&nbsp; &nbsp; &nbsp; <version&gt;6.7.2</version&gt;
&nbsp; &nbsp; </MavenReference&gt;
&nbsp; &nbsp; <MavenReference Include="org.flowable:flowable-http-common"&gt;
&nbsp; &nbsp; &nbsp; <groupId&gt;org.flowable</groupId&gt;
&nbsp; &nbsp; &nbsp; <artifactId&gt;flowable-http-common</artifactId&gt;
&nbsp; &nbsp; &nbsp; <version&gt;6.7.2</version&gt;
&nbsp; &nbsp; </MavenReference&gt;
&nbsp; &nbsp; <MavenReference Include="com.h2database:h2"&gt;
&nbsp; &nbsp; &nbsp; <groupId&gt;com.h2database</groupId&gt;
&nbsp; &nbsp; &nbsp; <artifactId&gt;h2</artifactId&gt;
&nbsp; &nbsp; &nbsp; <version&gt;1.4.200</version&gt;
&nbsp; &nbsp; </MavenReference&gt;
&nbsp; </ItemGroup&gt;


&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerome ***@***.***&gt;; 
发送时间: 2022年9月27日(星期二) 晚上10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ikvm-revived/ikvm] catch ClassNotFoundException does not work (Issue #171)





 
I'm sorry, I have no idea from this post what you are trying to do, what JAR file you converted, how you converted it, etc.
 
&mdash;
