### ISSUE TITLE
.Net Core compatible version to NuGet

### ISSUE THREAD

**Issue by nicksalt** [ikvm-revived/ikvm#19]
Hello,

Is there currently a plan in the works to publish the .Net Core compatible branch to NuGet?

Thank you

**Comment by NightOwl888** [comment]
There has been some progress - the build chain has been converted to use the new `.csproj` format in #17. However, there hasn't been any work done since late March and although that branch appears to be ready to merge, the approval process has apparently stalled.

**Comment by erksch** [comment]
The pull request was merged :D Can we help bringing a .NET Core version to NuGet?

**Comment by ol65** [comment]
Hi, any news about this? What is the name of the nuget - package?

**Comment by ams-tschoening** [comment]
There's no newer nuget package I'm aware of:

https://www.nuget.org/packages/IKVM.WINDWARD/

**Comment by NightOwl888** [comment]
We now have a prerelease that supports .NET Core on NuGet: https://www.nuget.org/packages/IKVM/8.2.0-prerelease0379
