### ISSUE TITLE
Unable to run Jython standalone jar

### ISSUE THREAD

**Issue by 3oheicrw-alter-ego** [ikvm-revived/ikvm#192]
This is Jython: https://www.jython.org/download.html

I have tested all versions up to 2.7.0. Only 2.7.0 is able to run but it's very slow. All later versions can't run.

**Comment by 3oheicrw-alter-ego** [comment]
It could be because I setup it wrong. Please help: https://github.com/ikvm-revived/ikvm/discussions/191

**Comment by wasabii** [comment]
For context: the message that was deleted:

[3oheicrw-alter-ego](https://github.com/3oheicrw-alter-ego)

>Try downloading it and run it yourself and you will see. Why are you that lazy? You will have to download and try it anyway if you really want to know what's going on. You can't debug something just by asking someone else running it and give the feedback to you. People's feedback is only meant to confirm the problem is fixed or not. If you think your time is precious then I will not bother you any further. Bye.

**Comment by wasabii** [comment]
Also, in response to this and the other issue #193, I added a Code Of Conduct to the develop branch. Copied from the DotNet foundation.

**Comment by 3oheicrw-alter-ego** [comment]
I don't care about your hypocrisy words. You show to others that you are good and I'm bad. They will appreciate you and think I'm an asshole. I don't care about this project anymore. You don't care about me and don't want me to use your software. So I do what you wanted me to do, going away from it.

> "It doesn't work" will never suffice.

Yeah, it should be. Other than you really don't care WTF about me. The discussion thread I linked that I'm asking for help how to setting this up, you have never cared enough to ever have a look at it. You only keen to close issues. You could do better than just closing it. But you don't. You could tell me to add more information. I will do. Even though I don't know what to add. A bunch of error messages that have no meanings for me, that I don't understand but could be sure that they have very little meanings to be useful at all. In case you are too lazy (oh you don't care about me anyway, your time is precious!), the error is about hawjni. If you ever download it and try yourself, you will see why I didn't give any output of it here. Because this output is mostly useless!

> Also, in response to this and the other issue #193, I added a Code Of Conduct to the develop branch. Copied from the DotNet foundation.
> 
> So at least [3oheicrw-alter-ego](https://github.com/3oheicrw-alter-ego) motivated me to fix one thing. Consider it pro-bono.

Keep your CoC and worship it yourself, no one other than you will ever contribute to this project. This will be my last message here. Your attitude is always unwelcoming, I did read other issues submitted by people and you did treat them the same or even worse. You are so keen to censor issues. Keep this software for your own use, because no one other than you will ever use it!
