### ISSUE TITLE
Unable to run RingoJS

### ISSUE THREAD

**Issue by 3oheicrw-alter-ego** [ikvm-revived/ikvm#193]
It's ringojs-4.0.0.zip: https://github.com/ringo/ringojs/releases/tag/v4.0.0

I edited the batch scripts to use ikvm instead of java.

Running ringo.bat crashed ikvm.exe.

**Comment by 3oheicrw-alter-ego** [comment]
Update: it's weird that I could run ringojs-4.0.0\lib\rhino-1.7.14.jar just fine.

**Comment by wasabii** [comment]
This issue contains no information that describes the error or problem being encountered.

**Comment by 3oheicrw-alter-ego** [comment]
> This issue contains no information that describes the error or problem being encountered.

Keep this shit for your own use. In the name of the lord, I will never use it again.

**Comment by wasabii** [comment]
For context, the message that was deleted:

[3oheicrw-alter-ego](https://github.com/3oheicrw-alter-ego)

>Keep this shit for your own use. In the name of the lord, I will never use it again.
