### ISSUE TITLE
8.3.2: MSBuild tasks broken on Core: TaskHostFactory is coded for Windows

### ISSUE THREAD

**Issue by kb-1000** [ikvm-revived/ikvm#213]
Additionally, neither the IKVM NuGet package nor building the project itself work on Linux (with .NET Core/5/6/7)

**Comment by wasabii** [comment]
So, on the image artifact, yeah. I need to change that to .tar.gz on Linux.

On NuGet, the executable bits should be set by the build system. What issue are you seeing?

IKVM itself cannot be built on Linux, currently, no.

**Comment by kb-1000** [comment]
It actually isn't necessary to use a tar file to get executable bits, zips support that just fine, as long as the source has them and the tool you use to create them supports UNIX extensions.
As you said, it can't be built on Linux, and Windows doesn't really have that (using a tar wouldn't change that fact).

As for NuGet:
```
[user@laptop-host ikvmtest]$ dotnet build ikvmtest.csproj 
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/home/user/.nuget/packages/ikvm.msbuild/8.3.2/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(22,9): error MSB4216: Could not run the "IkvmGetReferenceAssemblies" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "/usr/lib64/dotnet/sdk/6.0.110/MSBuild.exe" exists and can be run. [/home/user/ikvmtest/ikvmtest.csproj]
/home/user/.nuget/packages/ikvm.msbuild/8.3.2/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(23,13): error MSB4028: The "IkvmGetReferenceAssemblies" task's outputs could not be retrieved from the "ResolvedFrameworkReferences" parameter. Object does not match target type. [/home/user/ikvmtest/ikvmtest.csproj]

Build FAILED.

/home/user/.nuget/packages/ikvm.msbuild/8.3.2/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(22,9): error MSB4216: Could not run the "IkvmGetReferenceAssemblies" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "/usr/lib64/dotnet/sdk/6.0.110/MSBuild.exe" exists and can be run. [/home/user/ikvmtest/ikvmtest.csproj]
/home/user/.nuget/packages/ikvm.msbuild/8.3.2/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(23,13): error MSB4028: The "IkvmGetReferenceAssemblies" task's outputs could not be retrieved from the "ResolvedFrameworkReferences" parameter. Object does not match target type. [/home/user/ikvmtest/ikvmtest.csproj]
    0 Warning(s)
    2 Error(s)
```
created by `dotnet new sln; dotnet new console`, editing the .csproj to set the target to netcoreapp3.1 (not necessary to reproduce the issue but I believe it's necessary for IKVM to work) and `dotnet add package IKVM`.

**Comment by wasabii** [comment]
Hmm. I just did dotnet new sln; dotnet new console, etc. Added a PackageReference for IKVM/8.2.3, and built it, and it built fine.

**Comment by wasabii** [comment]
Added an IkvmReference to a Jar file, and that worked too.

```
jhaltom@KYOTO:~/foo$ dotnet build jhaltom.csproj
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/home/jhaltom/.nuget/packages/ikvm/8.2.3/buildTransitive/netstandard2.0/IKVM.targets(100,9): warning : IKVM.NET Compiler (8.2.3+Branch.main.Sha.a281da3bc1416927608a96e332d6eed7e829b402) [/home/jhaltom/foo/jhaltom.csproj]
/home/jhaltom/.nuget/packages/ikvm/8.2.3/buildTransitive/netstandard2.0/IKVM.targets(100,9): warning : Copyright © 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug [/home/jhaltom/foo/jhaltom.csproj]
/home/jhaltom/.nuget/packages/ikvm/8.2.3/buildTransitive/netstandard2.0/IKVM.targets(100,9): warning :  [/home/jhaltom/foo/jhaltom.csproj]
  jhaltom -> /home/jhaltom/foo/bin/Debug/net7.0/jhaltom.dll

Build succeeded.

/home/jhaltom/.nuget/packages/ikvm/8.2.3/buildTransitive/netstandard2.0/IKVM.targets(100,9): warning : IKVM.NET Compiler (8.2.3+Branch.main.Sha.a281da3bc1416927608a96e332d6eed7e829b402) [/home/jhaltom/foo/jhaltom.csproj]
/home/jhaltom/.nuget/packages/ikvm/8.2.3/buildTransitive/netstandard2.0/IKVM.targets(100,9): warning : Copyright © 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug [/home/jhaltom/foo/jhaltom.csproj]
/home/jhaltom/.nuget/packages/ikvm/8.2.3/buildTransitive/netstandard2.0/IKVM.targets(100,9): warning :  [/home/jhaltom/foo/jhaltom.csproj]
    3 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.28
```

**Comment by kb-1000** [comment]
Interesting, seems like it's broken if your latest SDK is .NET 6 but not if it's .NET 7.
Installed a preview version of Fedora's .NET 7 package, appears to work with that. But that does still sound like something that should be fixed, and .NET 6 is LTS too.

**Comment by wasabii** [comment]
well, I tried to use global.json to set down my SDK version to 6, since I had the same thought, and it works fine. Haven't tried uninstalling though.

I'm not sure there's much of my own code that could be hte culprit here. The files are in the right place. There are only a handful of lines that make a distinction about how to configure the task:

```


    <PropertyGroup>
        <IkvmMSBuildTaskFolder Condition=" '$(MSBuildRuntimeType)' == 'Core' ">netcoreapp3.1</IkvmMSBuildTaskFolder>
        <IkvmMSBuildTaskFolder Condition=" '$(MSBuildRuntimeType)' != 'Core' ">net472</IkvmMSBuildTaskFolder>
        <IkvmMSBuildTaskAssembly>$(MSBuildThisFileDirectory)..\..\tasks\$(IkvmMSBuildTaskFolder)\IKVM.MSBuild.Tasks.dll</IkvmMSBuildTaskAssembly>
        <IkvmCompilerToolPath>@(IkvmCompilerToolPath->WithMetadataValue('TargetFramework', '$(IkvmToolFramework)')->WithMetadataValue('RuntimeIdentifier', '$(IkvmToolRuntime)'))</IkvmCompilerToolPath>
        <IkvmExporterToolPath>@(IkvmExporterToolPath->WithMetadataValue('TargetFramework', '$(IkvmToolFramework)')->WithMetadataValue('RuntimeIdentifier', '$(IkvmToolRuntime)'))</IkvmExporterToolPath>
    </PropertyGroup>

    <UsingTask TaskName="IkvmGetReferenceAssemblies" AssemblyFile="$(IkvmMSBuildTaskAssembly)" TaskFactory="TaskHostFactory" Condition="Exists('$(IkvmMSBuildTaskAssembly)')" />

```


The choice of which assembly to use is pretty obvious. MSBuild says it's Core, use the netcoreapp3.1 on. Else use the net461 one. And then UsingTask. I'm not in control of my besides that.

**Comment by wasabii** [comment]
Also, this was working fine for me for the last few months. Before I even had 7 on my machine. 

My guess is something up with your install.

**Comment by kb-1000** [comment]
This is a rather fresh install, and I'm able to reproduce this on my other local machine (both running Fedora 36) as well.
Also tried on a Ubuntu 22.04 server (this is the first time I installed or did anything .NET on it), can reproduce there as well.

**Comment by wasabii** [comment]
What version of MSBuild are all of these showing? My Ubuntu install with dotnet 6 is showing 17.3

**Comment by kb-1000** [comment]
All three show 17.0.1+b177f8fa7.
You're probably using the snap version which is on 17.3.2+561848881 (which segfaults for me? but long before any of your stuff is loaded)

**Comment by wasabii** [comment]
Switch to the .NET 6 build into Ubuntu (purged out all the Microsoft source packages).... still works fine.

**Comment by wasabii** [comment]
Haha. I got it. My bad. I had transposed the version I was testing. 8.2.3 vs 8.3.2.

Found the issue. TaskHostFactory is broken on Core it looks like.

**Comment by wasabii** [comment]
So, 8.2.3 works. So that might tide you over while I get this fixed.
