### ISSUE TITLE
Remove Old Nant Scripts

### ISSUE THREAD

**Issue by tr33s** [ikvm-revived/ikvm#22]
a9989ea breaks nant building, although I'm not sure if that was intended.

CommonAssemblyInfo.cs.in was deleted in that commit, and is still referenced by ikvm.build.

_Originally posted by @tr33s in https://github.com/ikvm-revived/ikvm/pull/17#issuecomment-636605034_

**Comment by NightOwl888** [comment]
The nant scripts have been replaced with MSBuild files with the [new `.csproj` format](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj). The old nant scripts are only being kept around for reference as we work out how to finish the conversion to .NET Standard.

**Comment by tr33s** [comment]
Alright, well I got the project running with MSBuild, thanks.

Requesting README and HOWTO be updated as well.

**Comment by AaronRobinsonMSFT** [comment]
@NightOwl888 Is there a plan to fold some of the native build into an existing SDK project? Given the native build is so simple, it would be relatively easy to create a native build sub-task in `IKVM.Runtime.JNI.csproj`. Thoughts?

**Comment by NightOwl888** [comment]
The old NAnt scripts have been removed in the main branch, and we have also updated the readme with some build details (let us know if we need to add more details). There is also now a prerelease on NuGet: https://www.nuget.org/packages/IKVM/8.2.0-prerelease0379
