### ISSUE TITLE
8.4.0: release zip files appear to be invalid

### ISSUE THREAD

**Issue by joniles** [ikvm-revived/ikvm#242]
Downloading [IKVM-8.4.0-bin-net461.zip](https://github.com/ikvm-revived/ikvm/releases/download/8.4.0/IKVM-8.4.0-bin-net461.zip) to a Windows 10 machine, the zip functionality in File Explorer is unable to unzip the file, and neither can 7-Zip or WinZip. This appears to be an issue with other zip files I've tried from this release. I am able to successfully unzip the same files from the 8.3.3 release.

**Comment by ams-tschoening** [comment]
It's some kind of additional image in the ZIP. I'm able to extract the content using WinRar, rename to ZIP and see content:

![Screenshot level 1](https://user-images.githubusercontent.com/6223655/209803042-1f3cc4d4-2488-4c6b-8b6f-a89aae1c0986.png)

![Screenshot level 2](https://user-images.githubusercontent.com/6223655/209803068-d3387c8a-990b-4623-b41d-6ccc47331d39.png)

![Screenshot HxD](https://user-images.githubusercontent.com/6223655/209803234-b226dcc5-b6a1-41a5-90f8-b78d7e3b0037.png)

**Comment by wasabii** [comment]
Huh. Wonder what happened here. That looks like a tgz.

**Comment by wasabii** [comment]
Okay. There we go. These rarely get tested. 8.4.0 introduced tar.gz versions of the files (now that Linux support is pretty reasonable), but clobbered the zip with the tar during the release process.

8.4.1 will have this resolved.
