### ISSUE TITLE
DynamicMethodUtils.Create Issue

### ISSUE THREAD

**Issue by williamOlden** [ikvm-revived/ikvm#253]
Ran into a system path issue with
IKVM.Runtime.DynamicMethodUtils.Create()

```
AssemblyBuilder assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly(new AssemblyName("<DynamicMethodHolder>"), AssemblyBuilderAccess.RunAndCollect);
Interlocked.CompareExchange<Module>(ref DynamicMethodUtils.dynamicModule, assemblyBuilder.DefineDynamicModule("<DynamicMethodHolder>"), null);
```

But removing the "<" and ">" fixed the path issues.

```
AssemblyBuilder assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly(new AssemblyName("DynamicMethodHolder"), AssemblyBuilderAccess.RunAndCollect);
Interlocked.CompareExchange<Module>(ref DynamicMethodUtils.dynamicModule, assemblyBuilder.DefineDynamicModule("DynamicMethodHolder"), null);
```

**Comment by wasabii** [comment]
What do you mean path issue?

**Comment by williamOlden** [comment]
I don't have the error on me, but I believe the error was "ArgumentException Illegal Characters in Path"

**Comment by wasabii** [comment]
Yeah, but for what?

I'm not completely sure what you're trying to do. A dynamic method should have nothing to do with saving or paths or anything.

**Comment by wasabii** [comment]
Geeze. I think I figured it out. Gotta think through this.

This is from the Mono code:

>if (Path.GetFileName (fileName) != fileName)
>				throw new ArgumentException ("fileName '" + fileName + "' must not include a path.", "fileName");

**Comment by williamOlden** [comment]
Yup that was the format of the error

**Comment by wasabii** [comment]
It calls Path.GetFileName even if the 'transient' argument is passed as true, which means there is no intention to ever save the assembly. This is def a Mono bug.

**Comment by wasabii** [comment]
mono/mono#21601

**Comment by wasabii** [comment]
I'm going to work around it here by conditioning the name on Mono.
