### ISSUE TITLE
Cannot find assembly - System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1

### ISSUE THREAD

**Issue by IgnacioHR** [ikvm-revived/ikvm#256]
I'm in the process to update one of our products. It is an Excel Add On that uses our library in Java.

Actually the compilation success, but when testing, Excel open a big message screen with this information.

This is maybe our problem. I'm not sure, I'm just doing what the initial part of the message suggest (file a bug...)

---------------------------
IKVM.NET 8.4.4.0 Critical Failure
---------------------------
****** Critical Failure: Loading of critical class failed ******

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

(on Windows you can use Ctrl+C to copy the contents of this message to the clipboard)

IKVM.Runtime, Version=8.4.4.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\

4.0.30319.42000 64-bit

System.IO.FileLoadException: No se puede cargar el archivo o ensamblado 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)

Nombre de archivo: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   en System.ReadOnlyMemory`1.get_Span()

   en IKVM.Internal.AssemblyClassLoader.AssemblyLoader.DoLoad(String name)

   en IKVM.Internal.AssemblyClassLoader.DoLoad(String name)

   en IKVM.Internal.AssemblyClassLoader.FindLoadedClassLazy(String name)

   en IKVM.Internal.ClassLoaderWrapper.FindLoadedClass(String name)

   en IKVM.Internal.AssemblyClassLoader.LoadClassImpl(String name, LoadMode mode)

   en IKVM.Internal.ClassLoaderWrapper.LoadClass(String name, LoadMode mode)

   en IKVM.Internal.ClassLoaderWrapper.LoadClassCritical(String name)

=== Información de estado anterior al enlace ===

LOG: DisplayName = System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)

LOG: Appbase = file:///C:/Users/Ignacio/git/Install/RSExcelToXBRLMapping/ExcelAddIn/bin/Release/

LOG: PrivatePath inicial = NULL

Ensamblado de llamada : System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.

===

LOG: Este enlace empieza en el contexto de carga default.

LOG: No se encontró ningún archivo de configuración de la aplicación.

LOG: Utilizando el archivo de configuración de host: 

LOG: Utilizando el archivo de configuración del equipo en C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.

LOG: Referencia posterior a la directiva: System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

LOG: Intento de descarga de la nueva dirección URL file:///C:/Users/Ignacio/git/Install/RSExcelToXBRLMapping/ExcelAddIn/bin/Release/System.Runtime.CompilerServices.Unsafe.DLL.

AVS: Al comparar el nombre de ensamblado se generó la incompatibilidad: Versión principal

ERR: Error al completar la instalación del ensamblado (hr = 0x80131040). Finalizó la búsqueda.

   en System.ReadOnlyMemory`1.get_Span()

   en IKVM.Internal.AssemblyClassLoader.AssemblyLoader.DoLoad(String name)

   en IKVM.Internal.AssemblyClassLoader.DoLoad(String name)

   en IKVM.Internal.AssemblyClassLoader.FindLoadedClassLazy(String name)

   en IKVM.Internal.ClassLoaderWrapper.FindLoadedClass(String name)

   en IKVM.Internal.AssemblyClassLoader.LoadClassImpl(String name, LoadMode mode)

   en IKVM.Internal.ClassLoaderWrapper.LoadClass(String name, LoadMode mode)

   en IKVM.Internal.ClassLoaderWrapper.LoadClassCritical(String name)

   en IKVM.Internal.JVM.CriticalFailure(String message, Exception x)

   en IKVM.Internal.ClassLoaderWrapper.LoadClassCritical(String name)

   en IKVM.Internal.ClassLoaderWrapper.GetWrapperFromType(Type type)

   en IKVM.Internal.ClassLoaderWrapper.GetWrapperFromType(Type type)

   en IKVM.Java.Externs.ikvm.runtime.Util.GetTypeWrapperFromObject(Object o)

   en IKVM.Java.Externs.ikvm.runtime.Util.getClassFromObject(Object o)

   en ikvm.runtime.Util.getClassFromObject(Object o)

   en java.lang.Object.instancehelper_getClass(Object this)

   en java.util.Arrays.copyOf(Object[] original, Int32 newLength)

   en java.util.ArrayList.grow(Int32 minCapacity)

   en java.util.ArrayList.ensureExplicitCapacity(Int32 minCapacity)

   en java.util.ArrayList.ensureCapacityInternal(Int32 minCapacity)

   en java.util.ArrayList.add(Object e)

   en sun.misc.Unsafe.allocateUnsafeFieldId(Field original)

   en sun.misc.Unsafe.objectFieldOffset(Class c, String field)

   en java.util.concurrent.ConcurrentHashMap..cctor()

   en java.util.concurrent.ConcurrentHashMap..ctor()

   en org.apache.logging.log4j.MarkerManager..cctor() en MarkerManager.java:línea 31

   en org.apache.logging.log4j.MarkerManager.getMarker(String name)

   en org.apache.logging.log4j.spi.AbstractLogger..cctor() en AbstractLogger.java:línea 64

   en org.apache.logging.log4j.spi.AbstractLogger.__<clinit>()

   en org.apache.logging.log4j.status.StatusLogger..cctor() en StatusLogger.java:línea 78

   en org.apache.logging.log4j.status.StatusLogger.getLogger()

   en org.apache.logging.log4j.LogManager..cctor() en LogManager.java:línea 61

   en org.apache.logging.log4j.LogManager.getLogger(Class clazz)

   en com.ihr.xbrl.util.RSStaticAndUser..cctor()

   en com.ihr.xbrl.util.RSStaticAndUser.getUserPropertiesFileName(String str)

   en ExcelXBRLMapper.RibbonMapper.ReadProperties() en C:\Users\Ignacio\git\Install\RSExcelToXBRLMapping\ExcelAddIn\RibbonMapper.cs:línea 341

   en ExcelXBRLMapper.RibbonMapper.Ribbon_Load(IRibbonUI ribbonUI) en C:\Users\Ignacio\git\Install\RSExcelToXBRLMapping\ExcelAddIn\RibbonMapper.cs:línea 152

   en System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   en System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   en System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

---------------------------
Aceptar   
---------------------------

**Comment by wasabii** [comment]
I can't quite fully translate this. But it looks like either a missing assembly, or a missing assembly version?

**Comment by wasabii** [comment]
My guess is this is going to have to do with your assembly binding redirects. MSBuild should be generating your app.config file with the correct binding redirects.... but that's really an aspect of your build system.

And of course Excel has to be respecting binding redirects, which i have no idea about.

**Comment by IgnacioHR** [comment]
At the time the project is compiled the following warnings are raised:

WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'System.Memory.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'System.Threading.Tasks.Extensions.dll'

Those files exists in the same folder where ikvmc.exe is located, but the version is 4.6.31308
In Visual Studio 2019, the project has been set to use .NET Framework 4.6.1 (because I downloaded that specific version) Previously, the project was using .NET Framework 4.0 Client Profile because that was the version required for the Excel AddIn library.

I've to confess I'm a bit lost in regard to Microsoft nuances...

**Comment by wasabii** [comment]
ikvmc doesn't matter for this, so I'm not sure about that. ikvmc should not be distributed with any of this.

**Comment by wasabii** [comment]
You're probably going to need to get familiar with how assembly binding works on Framework: https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by IgnacioHR** [comment]
Thanks for the link

**Comment by wasabii** [comment]
https://stackoverflow.com/questions/25664372/making-binding-redirects-work-for-office-add-ins

**Comment by wasabii** [comment]
Can I ask how you're building any of this? The fact that you care about ikvmc at all is weird. Modern IKVM is done through NuGet.

**Comment by IgnacioHR** [comment]
We compile our java code and generate a file called xbrljlib2.0.jar
We use ikvmc.exe to generate xbrljlib2.0.dll 
Then, in a separate project using c# source code we reference xbrljlib2.0.dll and we use the java classes as if they was c# classes.
The only differences are that xbrljlib2.0.dll is now developed using ikvmc.exe for .NET framework 4.6.1 but the Office framework we are using is 4.0
I think the problem is there and I'm searching for the availability of Office framework for 4.6 or later

**Comment by wasabii** [comment]
Okay. So if you aren't using MSBuild to build, it's not going to generate your assembly bindings.

IKVM allows you to directly reference JAR files from MSBuild projects now. IkvmReference.

And we also have a special project type which can directly compile Java source.

**Comment by IgnacioHR** [comment]
Well, we are using MSBuild to build the Excel Add In

**Comment by wasabii** [comment]
> Well, we are using MSBuild to build the Excel Add In

But not the Java.

**Comment by IgnacioHR** [comment]
> Remember, we've adopted modern .net stuff now. Your projects should be doing the same for full support.

This is definitively the key point. The project is pretty old and requires a deep revision

**Comment by IgnacioHR** [comment]
I'm going to close this issue because we need to do the research about how to avoid the use of ikvmc at all.

**Comment by wasabii** [comment]
Still means the assembly bindings are incorrect.

**Comment by wasabii** [comment]
None of that has to do with assembly binding redirects. You really need to generate a file to redirect them.

**Comment by wasabii** [comment]
Please review the links I had previously set about how binding redirects work in .NET Framework.

**Comment by IgnacioHR** [comment]
I'll try to write an app.config and specify explicitly the redirection. The question is, What shall I redirect from/to? The project is quite simple

<img width="323" alt="Window-2" src="https://user-images.githubusercontent.com/16385090/212750568-b58f4683-740f-4c95-82db-56e792377a38.png">

**Comment by wasabii** [comment]
You really do not need to be doing this stuff by hand.

*sigh*

Please just use the tools provided and then if they don't work, start from there.

**Comment by IgnacioHR** [comment]
In the end, adding this line

```
<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```
to one of the `PropertyGroup` in `MyProject.csproj` did the trick! as the generated DLL could be loaded inside Excel.
