### ISSUE TITLE
IKVM error FreeLibrary Entry Point not Found with BioFormats.NET

### ISSUE THREAD

**Issue by BiologyTools** [ikvm-revived/ikvm#260]
I've already tried getting help from Bioformats library maintainers and FreeLibrary is not used by BioFormats.NET so FreeLibrary problem has to be in IKVM. Has anyone else ran into issues running IKVM on Linux. Bioformats works fine on Linux when creating ImageWriter but crashes when trying to create ImageReader. Throwing the following exception in MonoDevelop when using IKVM 8.3.3:
![image](https://user-images.githubusercontent.com/84872500/211382105-dfc01782-b7b1-4299-913c-0dc187b61578.png)

**Comment by wasabii** [comment]
Try 8.4.4. It's possible this was related to the JNI_OnLoad bug.

**Comment by wasabii** [comment]
#239

**Comment by BiologyTools** [comment]
@wasabii I can't add the latest IKVM as it doesn't work with Mono. ```Unable to find a version of 'Mono.Posix' that is compatible with 'IKVM 8.4.4 constraint: Mono.Posix (>= 7.1.0-final.1.21458.1)'.```

**Comment by wasabii** [comment]
What is producing that store?

**Comment by BiologyTools** [comment]
I get that error when trying to add the latest IKVM as a nuget package in Mono. I can only get 8.3.3 to successfully add to my project. Anything newer and I get that error.

**Comment by wasabii** [comment]
Sorry, I don't know exactly what you mean by that. It's a NuGet package. It's handled by the build system, not by Mono itself.

**Comment by BiologyTools** [comment]
I can't get the latest IKVM to run in mono because according to MonoDevelop it's not compatible. If I try to add IKVM in visual studio I get the same error. So I can't try your solution of using the latest version of IKVM.

**Comment by wasabii** [comment]
Well, I don't know what to say. It's likely a well known bug in < 8.4.4.

I can say a number of things though; MonoDevelop has been unmaintained for three years now. It was abandoned by MS. We no longer support non-SDK style projects.

The error, if you're getting it in VS, sounds like it can't find a version compatible with the version of the Runtime you're trying to use. We support .NET Framework 4.6.1+ and .NET Core 3.1+.

**Comment by BiologyTools** [comment]
@wasabii Thank you for your time. I will try to get 8.4.4 to work on Mono and hopefully I can get Bioformats.NET to work. There is a project called CellTool which runs Bioformats library with IKVM 8.1.5717 on Linux so maybe they can help.

**Comment by BiologyTools** [comment]
@wasabii Looks like the solution was to use the prelease IKVM 8.4.4-prerelease0001 it works just fine now with no errors. I've been trying for weeks to get this to work thanks! I know mono is about to be abandoned but I like the drag drop editing of Winforms rather than learning to use XAML with something like MAUI.

**Comment by wasabii** [comment]
Mono isn't about to be abandoned. MonoDevelop however *IS* abandoned and has been for three years at least.

Mono is just one the low end of things we support.

**Comment by BiologyTools** [comment]
Well I've been using DotDevelop instead of MonoDevelop since MonoDevelop was abandoned. I personally really like Winforms maybe because that's all I've ever used. Hopefully the community around dotdevelop manages to keep mono & the IDE in working order. This will be my first cross platform program and since the only similar program out there CellTool chose Mono I followed their lead. Since the user base will be Biologists the interface doesn't need to be modern just like ImageJ is very basic looking.

**Comment by wasabii** [comment]
Well, I mean... I don't know what to say. You've chosen an old technology stack, consisting of mostly abandoned or half abandoned projects. On the basis of an old mostly abandoned project also did it. I took a look at DotDevelop: there hasn't been a commit since last October. The last release was in 2020. Three years ago now. There are open issues on the issue tracker that haven't been answered in a month. As to CellTool, if you mean, https://github.com/GDanovski/CellTool, then that hasn't had a commit in two years. You've opened issues on it, and those have been unanswered for a week.

You're in for some pain keeping this going into the future.

**Comment by BiologyTools** [comment]
I just noticed how little C# libraries or programs exist for microscopy image stacks so I made a library for viewing them. That program then grew to editing them & integration to ImageJ. Most microscopes run on windows anyways so Unix & Mac's are rarely needed by end user. But I figured making the library cross platform was a good next goal.
