### ISSUE TITLE
ikvmc  unable to find 'netstandard.dll'.

### ISSUE THREAD

**Issue by rayanngage2** [ikvm-revived/ikvm#261]
D:\jarpack>ikvmc -out:bcp-sdk-1.0.0.RELEASE.dll bcp-sdk-1.0.0.RELEASE.jar -nostdlib -lib:D:\Program Files\IKVM-8.4.4-tools-netcoreapp3.1-win7-x64\refs\\*.dll
ikvmc (8.4.4+Branch.main.Sha.103f78408061ddcb58e3a5715ff02893ca0216b2)
Copyright ? 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

error IKVMC4005: Source file 'Files\IKVM-8.4.4-tools-netcoreapp3.1-win7-x64\refs\\*.dll' not found
Error: unable to find 'netstandard.dll'.

D:\jarpack>ikvmc -out:bcp-sdk-1.0.0.RELEASE.dll bcp-sdk-1.0.0.RELEASE.jar -nostdlib -lib:\IKVM-8.4.4-tools-netcoreapp3.1-win7-x64\refs\*.dll
ikvmc (8.4.4+Branch.main.Sha.103f78408061ddcb58e3a5715ff02893ca0216b2)
Copyright ? 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

warning IKVMC0124: Directory "\IKVM-8.4.4-tools-netcoreapp3.1-win7-x64\refs\\*.dll" specified in -lib option is not valid
Error: unable to find 'netstandard.dll'.

what can I do to fix it?

**Comment by rayanngage2** [comment]
D:\jarpack>dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by wasabii** [comment]
ikvmc does not parse wildcards.
