### ISSUE TITLE
IKVMC5025  and IKVMC0124

### ISSUE THREAD

**Issue by rayanngage2** [ikvm-revived/ikvm#263]
c:\jarpack>ikvmc -out:bcp-sdk-1.0.0.RELEASE.dll bcp-sdk-1.0.0.RELEASE.jar -nostdlib -lib:dotnet\shared\Microsoft.NETCore.App\3.1.32\netstandard.dll
ikvmc (8.4.4+Branch.main.Sha.103f78408061ddcb58e3a5715ff02893ca0216b2)
Copyright ? 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

warning IKVMC0124: Directory "dotnet\shared\Microsoft.NETCore.App\3.1.32\netstandard.dll" specified in -lib option is not valid
Error: unable to find 'netstandard.dll'.

c:\jarpack>ikvmc -out:bcp-sdk-1.0.0.RELEASE.dll bcp-sdk-1.0.0.RELEASE.jar -nostdlib -lib:IKVM-8.4.4-tools-netcoreapp3.1-win7-x64\netstandard.dll
ikvmc (8.4.4+Branch.main.Sha.103f78408061ddcb58e3a5715ff02893ca0216b2)
Copyright ? 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

warning IKVMC0124: Directory "IKVM-8.4.4-tools-netcoreapp3.1-win7-x64\netstandard.dll" specified in -lib option is not valid
Error: unable to find 'netstandard.dll'.

c:\jarpack>ikvmc -out:bcp-sdk-1.0.0.RELEASE.dll bcp-sdk-1.0.0.RELEASE.jar -nostdlib -r:\IKVM-8.4.4-tools-netcoreapp3.1-win7-x64\refs\netstandard.dll
ikvmc (8.4.4+Branch.main.Sha.103f78408061ddcb58e3a5715ff02893ca0216b2)
Copyright ? 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

fatal error IKVMC5025: Unable to load runtime assembly

I dong't know what can i do

**Comment by wasabii** [comment]
Did you read the readme?
