### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by hornpecom** [ikvm-revived/ikvm#27]
We would like to use the toolset IKVM.NET (as NuGet Package https://www.nuget.org/packages/IKVM.WINDWARD/) in our commercial product. Do we then have to release the source code to the end customers because of the IKVM.NET licensing? How do you proceed with the licensing of your products in which IKVM.NET is used? What is your recommendation in this case?

In the license terms we can find this
>   Some files in this distribution are part of GNU Classpath or OpenJDK and
>   are licensed under the GNU General Public License (GPL) version 2
>   with "Classpath" exception. This applies in particular to:
>     - IKVM.OpenJDK.*.dll

What about another DLL-Files like 
- IKVM.AWT.WinForms.dll
- IKVM.Runtime*.dll
- IKVM.Reflection.dll?

**Comment by ams-tschoening** [comment]
> What about another DLL-Files like

IKVM's own files use a [custom license](https://sourceforge.net/p/ikvm/wiki/License/) mostly, which you can find at the top of most/all files. You should be safe to not need to release your source code to customers, but if in doubt you simply need to ask specialized lawyers.

```
Copyright (C) 2002-2014 Jeroen Frijters

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.

Jeroen Frijters
jeroen@frijters.net
```

**Comment by ams-tschoening** [comment]
Test

**Comment by ams-tschoening** [comment]
test

**Comment by ams-tschoening** [comment]
test
