### ISSUE TITLE
Error: unable to find assembly 'IKVM.OpenJDK.Core

### ISSUE THREAD

**Issue by HyperSphereStudio** [ikvm-revived/ikvm#28]
Hello, I am new to building IKVM and I cant seem to get around this issue that appears when I am running the ikvmc.exe on a jar:

`warning IKVMC0134: Compiling stubs is deprecated. Please add a reference to assembly "IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58" instead.
Error: unable to find assembly 'IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58`

I built version 8.5.0.3 using this code + some of the ikvm8 AssemblyInfo.cs's.  .NET Framework 4.8 is being used, IKVM.OpenJDK.Core Version 8.5.0.3 exists but it is not being accepted as reference. I tried referencing the 8.1.5717.0 version; however, this caused another error as the runtime version did not match up anymore. I tried this on the ikvm8 with the same result. Anyone else experienced this / know how to fix this?

**Comment by ams-tschoening** [comment]
Guten Tag HyperSphereStudio,
am Donnerstag, 31. Dezember 2020 um 12:51 schrieben Sie:

> I built version 8.5.0.3 using this code + some of the ikvm8
> AssemblyInfo.cs's.

So you mixed things up on your own or how doesn one need to understand
this? From where exactly did you use with files and executed which
result?

Do you NEED to build from scratch? You can simply try the officially
released version mentioned in your error message for the start:

https://github.com/ams-ts-ikvm/ikvm-bin

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning
AM-SoFT IT-Service - Bitstore Hameln GmbH

E-Mail:  Thorsten.Schoening@AM-SoFT.de
Web:     http://www.AM-SoFT.de/

Telefon: 05151-  9468-55
Fax:     05151-  9468-88
Mobil:    0178-8 9468-04

Firmensitz: Bitstore IT-Consulting, Frankfurter Allee 285, 10317 Berlin
Steuernummer 037/230/30566, HR 27198, Amtsgericht Potsdam Geschäftsführer Janine Galonska

**Comment by HyperSphereStudio** [comment]
Sorry, wrote that at like 4 AM so it was not fully comprehensible.

I had tried the release you posted above; however, anytime I use a RandomAccessFile on v8.1.5717 I get this error:

cli.System.MissingMethodException: Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights, System.IO.FileShare, Int32, System.IO.FileOptions)'.
        at Java_java_io_FileDescriptor.open(Unknown Source)
        at java.io.FileDescriptor.open(Native Method)
        at java.io.FileDescriptor.open(FileDescriptor.java:365)
        at java.io.FileDescriptor.openReadOnly(FileDescriptor.java:336)
        at Java_java_io_RandomAccessFile.open0(Unknown Source)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)

I saw a similar post saying that net_core_compact would fix it; however, I get the same error as the one I posted before when I used that one. 

What I did was fill in files that build was throwing could not find exceptions for from previous projects that had it which basically was just the AssemblyInfo.cs.in's. This might have been the repo where I got them from, I am not sure, I have been trying literally every repo with v8.5 the same result so I feel like I am doing something wrong.

**Comment by HyperSphereStudio** [comment]
Solved with the following code in ikvmc/AssemblyResolver.cs

`if(assemblyDef.Name.Contains("IKVM.OpenJDK.Core") && assemblyRef.Name.Contains("IKVM.OpenJDK.Core")){
			    return true;
			}`

Also it seems that you need to make an uber jar rather than having jars zipped to main jar to compile using ikvmc
