### ISSUE TITLE
Generating stubs as an MSBuild task?

### ISSUE THREAD

**Issue by Oliver-makes-code** [ikvm-revived/ikvm#286]
I've set up dotnet to build a gradle project and include it's output JAR in the dotnet build, so I can use Kotlin with a C# project, but in order to properly interop the two, it'd be nice if I could automatically generate the stub when building

Here's the relevant parts of my current csproj file:
```xml
  <ItemGroup>
    <PackageReference Include="ikvm" Version="8.4.4" />
    <IkvmReference Include="build/libs/output.jar" />
  </ItemGroup>

  <Target Name="Gradle" BeforeTargets="BeforeBuild">
    <!-- I'd like to generate stub here -->
    <Exec Command="./gradlew build" />
  </Target>
```

**Comment by wasabii** [comment]
So I thought about this once, but pretty much decided MSBuild was the wrong place to put it. It probably more likely should be in Gradle for this usage.

That said, IKVM.Net.SDK does do this, since it builds Java classes directly.

And that's is a MSBuild Task for it.

**Comment by Oliver-makes-code** [comment]
> And there is a MSBuild Task for it.
What is the task for it?

**Comment by wasabii** [comment]
https://github.com/ikvm-revived/ikvm/blob/develop/src/IKVM.MSBuild.Tasks/IkvmExporter.cs

Exposed as `<IkvmExporter />` in the IKVM.MSBuild package. Beware about using these tasks outside IKVM itself. Though you can, we provide no guarantees as to their stability, etc. We might rename them, change their properties, etc, without notice, as suites our own purposes for IKVM and IKVM.NET.Sdk.
