### ISSUE TITLE
The reference is invalid or unsupported. (NET Core)

### ISSUE THREAD

**Issue by ismailkocacan** [ikvm-revived/ikvm#291]
I'm trying to use "IBM Informix JDBC Driver" via [maven repository](https://mvnrepository.com/artifact/com.ibm.informix/jdbc/4.50.9).

MyProject.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM" Version="8.4.5" />
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.4.1" />
  </ItemGroup>

	<ItemGroup>
		<MavenReference Include="jdbc">
			<GroupId>com.ibm.informix</GroupId>
			<ArtifactId>jdbc</ArtifactId>
			<Classifier></Classifier>
			<Version>4.50.9</Version>
		</MavenReference>
	</ItemGroup>

</Project>
```
jdbc.dll generated successfully. But I'm trying to add project reference getting this error (The reference is invalid or unsupported.)

![image](https://user-images.githubusercontent.com/3339197/219076803-3aee05dd-5924-4e29-9740-2b40388cdbb8.png)

Have you any suggestion ?

**Comment by wasabii** [comment]
Why are you trying to add a project reference?

**Comment by ismailkocacan** [comment]
> Why are you trying to add a project reference? You added it as a MavenReference......

I understand now.  :)  No need add to project reference.
@wasabii  You are great, you are perfect. Thank you so much.
