### ISSUE TITLE
File /lib/win7-x64/currency.properties not found exception when debugging 

### ISSUE THREAD

**Issue by BiologyTools** [ikvm-revived/ikvm#297]
When I upgraded from 8.4.0 to 8.5.0 while debugging I got the exception File not found  /lib/win7-x64/currency.properties I was able to get my application to run by telling the debugger to ignore the error so it's nothing critical but should be looked into. Strangely I have not run into this issue before so something has changed. 

Best, Erik

**Comment by wasabii** [comment]
Well, the thing that would concern me most is that the path should be `win7-x64/lib/currency.properties`, not as you've said, `lib/win7-x64/currency.properties`. I suspect this is a transposition on your part.

That said, the file isn't supposed to exist unless you add it.

**Comment by wasabii** [comment]
On the assumption you had the path incorrect, I'm going to go ahead and close this.

**Comment by BiologyTools** [comment]
![image](https://user-images.githubusercontent.com/84872500/224393425-320f9a98-b176-4944-8224-a29436cea70f.png)
I didn't happen to catch the exception last time but here is a screenshot.
