### ISSUE TITLE
Generic types are omitted

### ISSUE THREAD

**Issue by VahidN** [ikvm-revived/ikvm#299]
I'm trying to convert the latest [java-parser](https://github.com/javaparser/javaparser/tree/6f7bf20d1e44841fd5ff70dae8c4993e10136fe6) to a .NET assembly using the following settings:
```xml
  <ItemGroup>
    <PackageReference Include="IKVM" Version="8.4.5" />
  </ItemGroup>

  <ItemGroup>
    <IkvmReference Include="javaparser-core-3.25.1.jar" />
  </ItemGroup>
```
It compiles fine and produces the output .dll file, [but it converts](https://github.com/javaparser/javaparser/blob/6f7bf20d1e44841fd5ff70dae8c4993e10136fe6/javaparser-core/src/main/java/com/github/javaparser/ast/nodeTypes/NodeWithRange.java#L41) the following code:
```java
   default Optional<Position> getBegin() {
        return getRange().map(r -> r.begin);
    }
```
To this:
```C#
	[MethodImpl(MethodImplOptions.NoInlining)]
	[SpecialName]
	[LineNumberTable(42)]
	static Optional <default>getBegin(NodeWithRange P_0)
	{
		Optional result = P_0.getRange().map(new __<>Anon1());
		_ = null;
		return result;
	}
```
When I decompile the output .dll using the ILSpy, as you can see, its signature is just `Optional` and not the original `Optional<Position>`. Because its generics type info is omitted, it can't be used efficiently. Is there any solution for it?

**Comment by wasabii** [comment]
Java doesn't consider generics at runtime. So the code were generate also doesn't.

**Comment by GeorgeS2019** [comment]
@wasabii 

We may need to re-visit this issue IF it is relevant to JavaParser in the JavaToCsharp project!

If we could coordinate, it is important!

**Comment by wasabii** [comment]
Revisit what exactly? IKVM is a JVM implementation, not a language parser.
