### ISSUE TITLE
Nuget 8.50-069 install linux in Windows environment

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvm-revived/ikvm#300]
Is that necessary?

![image](https://user-images.githubusercontent.com/49812372/228293343-2ffd5c23-29d2-4ec3-99df-dd5a86343db2.png)

![image](https://user-images.githubusercontent.com/49812372/228293774-99b2ea9e-e174-4da2-bf49-cb41403ddd83.png)

**Comment by wasabii** [comment]
Yes. Just like .NET Core itself, having the Linux parts of the SDK is required for building .NET Core applications targeting Linux, when running on Windows.
