### ISSUE TITLE
How JavaToCsharp project complement Ikvm project?

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvm-revived/ikvm#301]
The [JavaParser ](https://github.com/javaparser/javaparser)used in [JavaToCsharp](https://github.com/paulirwin/JavaToCSharp/issues/44) project is actively updated on daily to weekly basis.

JavaToCsharp has the capability to handle AWT which is **NOT possible RIGHT NOW with this ikvm.** 

JavaToCsharp has a role to serve .NET community working on porting Java projects

**Comment by wasabii** [comment]
This doesn't seem to describe an issue in the IKVM project, a request for the IKVM project, or anything about IKVM I can sese.

**Comment by GeorgeS2019** [comment]
@wasabii 

You must not be short sighted. You need to allow AND support .NET community to come TOGETHER to enlighten you on what you do not see. 

Otherwise, Our best collective is ONLY as GOOD as What you could understand!!!

**Comment by wasabii** [comment]
Members of the JavaToCSharp project are perfectly able to open an issue or feature request if there is some need or requirement they want to raise. At present, this issue doesn't specify anything specific to do or to change. We don't need a bug report asking us to hang out or something.

**Comment by BiologyTools** [comment]
@GeorgeS2019 Does JavaToCSharp work with Mac? Currently IKVM doesn't support Mac.

**Comment by GeorgeS2019** [comment]
@BiologyTools

The purpose of JavaToCSharp is to create CSharp codes and U could then use dotnet in Mac

**Comment by GeorgeS2019** [comment]
@BiologyTools

@wasabii has technical talent, we need have more time to help him understand bigger picture

**Comment by BiologyTools** [comment]
Looks like IKVM is a much better option for my use case for .jar to .dll hopefully we get Mac support soon. Wasabi is an excellent dev.
