### ISSUE TITLE
interacting with dotnet libraries

### ISSUE THREAD

**Issue by Frontrider** [ikvm-revived/ikvm#302]
With this, can I use a dotnet library, as if it was a part of the java ecosystem? Or do anything to interact with a specific dotnet library?

**Comment by wasabii** [comment]
IKVM is a Java VM on top of .NET. Not the other way around.

**Comment by Frontrider** [comment]
No I meant calling down for a dotnet library, from java bytecode running on top of IKVM.

**Comment by wasabii** [comment]
Oh. Yeah.

**Comment by Frontrider** [comment]
Gonna be way too much effort (doable) for what I need. Interesting to see tough.
