### ISSUE TITLE
can't find cli.system.object

### ISSUE THREAD

**Issue by AndreAhmed** [ikvm-revived/ikvm#31]
I would like to access an existing .net dll using java code, therefore
I used ikvmstub to generate the jar file containing the generated
interface file.
However, when I try to compile this code from NetBeans, it fails with:

> class file for cli.System.IDisposable not found
> class file for cli.System.Object not found

Indeed, the stub jar-file does not contain those classes.
Are they located in some support library?

**Comment by NightOwl888** [comment]
Hi there. Does this problem still happen with the latest changes on the master branch?

**Comment by NightOwl888** [comment]
Closing as there has been a complete update of the build tools since this was posted. We now have a prerelease on NuGet at https://www.nuget.org/packages/IKVM/8.2.0-prerelease0379.
