### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by FlyingYu-Z** [ikvm-revived/ikvm#32]
i get this error when using OkHttp to visit url(https)

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

**Comment by wasabii** [comment]
Stale.

Though I'm assuming this is related to old TLS in the old version of OpenJDK we're running. Maybe.

**Comment by klangille** [comment]
I'm also hitting this problem. Is there any workaround or plan to update the OpenJDK version.

**Comment by wasabii** [comment]
#290

You can give the latest prerelease a try.

**Comment by klangille** [comment]
Thanks for the quick reply. I tested with 8.5.0-develop.2513 and got the same result. I can get around it by using http for now just wanted to see if a fix would be available soon. Thanks.
