### ISSUE TITLE
Missing System.Reflection methods on netcore compat branch

### ISSUE THREAD

**Issue by AlexanderFlesher** [ikvm-revived/ikvm#34]
An ikvmc converted dll is throwing an exception: 
`MissingMethodException: Method not found: 'System.Reflection.Emit.ModuleBuilder System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(System.String, System.String, Boolean)'.`

I was reading a little bit about this in another thread, where someone suggested referencing the System.Reflect nuget package. (I'm assuming they mean adding the package in IKVM before building it?) I couldn't quite figure that out. The nuget response when I attempt this is:
`Could not install package 'System.Reflection 4.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by NightOwl888** [comment]
The net_core_compat branch is now dead and so is the original issue.

> 1. Which branch of ikvm-revived to use?

We now have a prerelease (built from the [develop branch](https://github.com/ikvm-revived/ikvm/tree/develop)) available for testing: https://www.nuget.org/packages/IKVM/8.2.0-prerelease0379

> 2. Does anything special need to be done on the command line for ikvmc?

No. When you reported this, we didn't have a functional build for .NET Core. But the commands have not changed from the [ikvmc docs](https://sourceforge.net/p/ikvm/wiki/Ikvmc/).

> 3. If assemblies need to be referenced on ikvmc, how do I determine which ones? How do I find the full paths to the assemblies? Or maybe full paths MUST NOT BE used? Is the assembly name accessed at runtime?

ikvmc is a compiler, just like csc is. You must use ikvmc for each assembly you want to output, but the input can be various combinations of .jar files and .class files. The [ikvmc docs](https://sourceforge.net/p/ikvm/wiki/Ikvmc/) have some examples. You can use either relative or absolute paths to the Java assets you are building.

The tools for IKVM (ikvm, ikvmc, ikvmstub, etc) can be downloaded from the [releases page](https://github.com/ikvm-revived/ikvm/releases) (or from the [GitHub Actions artifacts](https://github.com/ikvm-revived/ikvm/actions)).

The [readme](https://github.com/ikvm-revived/ikvm/tree/develop#readme) on the develop branch now has build instructions, although most people won't need to build from source to use IKVM.

> 4. Do the Java JAR files need to be created initially with a very specific version of Java? Some are 3rd party outside my control. I know they are compatible with OpenJDK 8 U222 B10, because my Java app successfully uses them with that JRE.

IKVM supports the Java SE 8 specification. In general, most applications that would compile on Java 8 should function. Applications on newer versions of Java that conform to the Java SE 8 APIs can also work. See the [Java SE specifications](https://docs.oracle.com/javase/specs/) for API details and breaking changes.

> 5. I see that .NET Framework 4.5.2 has DefineDynamicModule method with the matching signature above, but I don't know how to get that to be used in my DLLs and/or .NET Core 3.1 or .NET 5.0 project. Reference: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder.definedynamicmodule?view=netframework-4.5.2

This project has just picked up from where it was left when the original team stopped maintaining it (back in 2015). Version 8.1.5717 and prior were compiled on .NET Framework 3.5, and it is not clear how well support works for .NET Framework 4.0 and higher for those old versions. However, our more recent prereleases are supported on .NET Framework 4.6.1 and higher as well as .NET Core 3.1 and higher. I suspect that `DefineDynamicModule` had breaking changes above .NET Framework 3.5 and that is why the tool doesn't convert assemblies right that utilize it.

> 6. If I have to reference an assembly name in ikvmc, do I also have to install that assembly in my Visual Studio project? I assume "yes" but need tips on which version, where to get it and how to install it.

After you build a set of assemblies or single assembly with ikvmc, they will have a dependency on the assemblies in the [IKVM NuGet package](https://www.nuget.org/packages/IKVM). So, your target project must both reference the converted assemblies and the IKVM NuGet package. There is no dependency on ikvmc, it is a compiler.

See the answer to question 3 for where to download ikvmc. The version of ikvmc you use must match the version of IKVM that you reference.
