### ISSUE TITLE
Mixed mode assembly error building ikvm-build branch

### ISSUE THREAD

**Issue by steveswett** [ikvm-revived/ikvm#35]
I'm trying to build the ikvm-build branch for the first time.  Following the How To and ReadMe files.  When I attempt to run "nant" in the c:\ikvm-ikvm-build directory, I get the following:

Unhandled Exception: System.IO.FileLoadException: Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.

Any idea how to resolve?

So far, the only thing unclear about the How To instructions was which JDK 8 bin path to add to the system PATH.

Ultimately, I'm trying to use a DLL created from a Java JAR in a Visual Studio .NET Core 3.1 or .NET 5.0 project.  Running into System.Reflection.Emit compatibility errors and trying a whole bunch of trial and error, including trying to build this project.

**Comment by wasabii** [comment]
@steveswett Are you interested in trying your efforts against our new develop branch?

**Comment by NightOwl888** [comment]
Closing, as this appears related to the old build, which is no longer relevant.
