### ISSUE TITLE
Anyone have openjdk-8u45-b14-stripped.zip

### ISSUE THREAD

**Issue by bogatykh** [ikvm-revived/ikvm#39]
http://www.frijters.net/openjdk-8u45-b14-stripped.zip is not available anymore.

Maybe someone has this archive downloaded to share?

**Comment by bogatykh** [comment]
Found GitHub repo of this:
https://github.com/joegana/openjdk-8u45-b14-stripped

**Comment by dkocher** [comment]
You might be interested in our work [upgrading IKVM to jdk8u312-b07 with support for TLSv1.3](https://github.com/iterate-ch/ikvm/commit/6b62850deb12350ce08aa5a1361bde127c972f77).

**Comment by ams-tschoening** [comment]
I've committed the original ZIP into my fork of IKVM some years ago as well:

https://github.com/ams-ts-ikvm/ikvm-src/tree/master/openjdk-8u45-b14
https://github.com/ams-ts-ikvm/ikvm-src/commit/60009f5bdb4c9db68121f393b8b4c790a326bd32#diff-01746c74b6239d0993405fd34080469a6d190950141b41b2fe5f22a0e9a2a10b

**Comment by joniles** [comment]
One more location: I found a copy when I needed it on archive.org: https://web.archive.org/web/20210816060013/http://www.frijters.net/openjdk-8u45-b14-stripped.zip

@dkocher your JDK update work looks great - will you be opening a PR back to this repo at some point?

**Comment by AliveDevil** [comment]
For reference purposes:
You can grab the OpenJDK 8 sources directly from HG ([Changeset for 8u45-b14](http://hg.openjdk.java.net/jdk8u/jdk8u/rev/15b679d327da)).
Create a linux virtual machine, install all dependencies as outlined [in their README-build.html](http://hg.openjdk.java.net/jdk8u/jdk8u/raw-file/tip/README-builds.html) (attention: That HTML is horrible)
Zip the resulting `build/linux-x86_64-normal-server-release`-folder and extract it.

Folder structure should look like:
* Repo Root
   * ikvm
   * jdk8u45-b14 (extracted source of JDK)
      * build
         * linux-x86_64-normal-server-release

This is _not_ a stripped version of JDK, but all required sources.

**Comment by AliveDevil** [comment]
@joniles 
> @dkocher your JDK update work looks great - will you be opening a PR back to this repo at some point?

Check here: https://github.com/ikvm-revived/ikvm/issues/40#issuecomment-989748771
Basically once this repo builds successfully we can start integrating the JDK8u312 update here.
