### ISSUE TITLE
System.MethodAccessException: MethodAccessException thrown in the compiled library when calling the runtime helper method

### ISSUE THREAD

**Issue by CYDHJ** [ikvm-revived/ikvm#47]
Run build.framework.cmd Build complete，No error，reference ikvm.*.dll in my project on runtime debug throw：

MethodAccessException:“[IKVM.OpenJDK.Core.dll]

Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations

Please help me, thank you。

**Comment by CYDHJ** [comment]
The DLL file generated by the project is successful, and the debugging report referenced to my project is as follows:
System. MethodAccessException:“[IKVM.OpenJDK.Core.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations。

Could you please help me solve this problem?

**Comment by CYDHJ** [comment]
Use not strong naming：
The assembly "ikvm. Openjdk. Core, version = 8.5.0.3, culture = neutral, publickeytoken = null" is marked as allowpartiallytrustedcallersattribute and uses a level 2 security transparency model. By default, level 2 transparency will cause all methods in the allowpartiallytrustedcallers assembly to become security transparent, which may be the cause of this exception.

**Comment by CYDHJ** [comment]
Decompile and view ikvm OpenJDK. Core. DLL found ikvm Runtime，IKVM. AWT. WinForms doesn't use publickey. Others use publickey. I don't know how to deal with it
[assembly: InternalsVisibleTo("IKVM.Runtime"]
[assembly: InternalsVisibleTo("IKVM.AWT.WinForms"]

**Comment by CYDHJ** [comment]
Assembly IKVM.OpenJDK.Core, Version 8.5.0.3

[assembly: AssemblyVersion("8.5.0.3")]
[assembly: Debuggable(true, false)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Core-ikvm-runtime-injected, PublicKey=00240000048000009400000006020000002400005253413100040000010001009D674F3D63B8D7A4C428BD7388341B025C71AA61C6224CD53A12C21330A3159D300051FE2EED154FE30D70673A079E4529D0FD78113DCA771DA8B0C1EF2F77B73651D55645B0A4294F0AF9BF7078432E13D0F46F951D712C2FCF02EB15552C0FE7817FC0AED58E0984F86661BF64D882F29B619899DD264041E7D4992548EB9E")]
[assembly: RemappedClass("java.lang.Object", typeof(object))]
[assembly: RemappedClass("java.lang.String", typeof(string))]
[assembly: RemappedClass("java.lang.Throwable", typeof(Exception))]
[assembly: RemappedClass("java.lang.Comparable", typeof(IComparable))]
[assembly: RemappedClass("java.lang.AutoCloseable", typeof(IDisposable))]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Security, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Beans, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: AssemblyCopyright("This software is licensed under the GNU General Public License version 2 + \"Classpath\" exception.\r\nSee http://www.gnu.org/software/classpath/license.html for details.\r\nCopyright")]
[assembly: AssemblyTitle("IKVM.NET OpenJDK Library for .NET")]
[assembly: AssemblyProduct("IKVM.NET")]
[assembly: AssemblyCompany("Jeroen Frijters")]
[assembly: AssemblyInformationalVersion("8.5.0.3")]
[assembly: InternalsVisibleTo("IKVM.Runtime")]
[assembly: InternalsVisibleTo("IKVM.AWT.WinForms")]
[assembly: AllowPartiallyTrustedCallers]
[assembly: Extension]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Util, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Corba, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.XML.API, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.XML.XPath, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.XML.Parse, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.XML.Transform, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.XML.Bind, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.SwingAWT, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.XML.WebServices, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.XML.Crypto, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Charsets, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Text, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Management, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Remoting, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Misc, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Naming, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Jdbc, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Media, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]
[assembly: InternalsVisibleTo("IKVM.OpenJDK.Nashorn, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0")]

**Comment by NightOwl888** [comment]
Thanks for the report.

AFAIK, we haven't yet solved all of the issues relating to building on .NET Framework and it is unknown why we are having build issues at this point. This project is primarily focused on .NET Core support, and the `build.core.cmd` command is succeeding on the master branch.

If you .NET Framework support, do note there is a [stable version on NuGet](https://www.nuget.org/packages/IKVM/8.1.5717) that you can use, which should correspond to the https://github.com/ikvm-revived/ikvm/tree/v8_1_5717_0 branch in this repo, which you might have better luck building for.

If you wish to get us out of the weeds and help drive this project forward, the errors you are seeing are apparently due to inconsistent `InternalsVisibleTo` support across all of the assemblies on .NET Framework. We use MSBuild to [generate the `InternalsVisibleTo` attributes](https://github.com/ikvm-revived/ikvm/blob/66416c5adb055981da0541b4a129c4bcebc30ea2/Directory.Build.targets#L27-L34) based on [configuration settings like these](https://github.com/ikvm-revived/ikvm/blob/66416c5adb055981da0541b4a129c4bcebc30ea2/ikvmc/ikvmc.csproj#L55-L65) in each `.csproj` file. If strong naming is enabled using [`<SignAssembly>true</SignAssembly>`](https://github.com/ikvm-revived/ikvm/blob/master/Directory.Build.props#L14) (which is enabled by default), these attributes will be generated with the [PublicKey specified here](https://github.com/ikvm-revived/ikvm/blob/master/Directory.Build.props#L13). You would need to dig through the old `.build` files (which are no longer in use, but kept around from the old build process to troubleshoot issues like these) to work out which parts we are missing to successfully build on .NET Framework.

**Comment by CYDHJ** [comment]
> Thanks for the report.
> 
> AFAIK, we haven't yet solved all of the issues relating to building on .NET Framework and it is unknown why we are having build issues at this point. This project is primarily focused on .NET Core support, and the `build.core.cmd` command is succeeding on the master branch.
> 
> If you .NET Framework support, do note there is a [stable version on NuGet](https://www.nuget.org/packages/IKVM/8.1.5717) that you can use, which should correspond to the https://github.com/ikvm-revived/ikvm/tree/v8_1_5717_0 branch in this repo, which you might have better luck building for.
> 
> If you wish to get us out of the weeds and help drive this project forward, the errors you are seeing are apparently due to inconsistent `InternalsVisibleTo` support across all of the assemblies on .NET Framework. We use MSBuild to [generate the `InternalsVisibleTo` attributes](https://github.com/ikvm-revived/ikvm/blob/66416c5adb055981da0541b4a129c4bcebc30ea2/Directory.Build.targets#L27-L34) based on [configuration settings like these](https://github.com/ikvm-revived/ikvm/blob/66416c5adb055981da0541b4a129c4bcebc30ea2/ikvmc/ikvmc.csproj#L55-L65) in each `.csproj` file. If strong naming is enabled using [`<SignAssembly>true</SignAssembly>`](https://github.com/ikvm-revived/ikvm/blob/master/Directory.Build.props#L14) (which is enabled by default), these attributes will be generated with the [PublicKey specified here](https://github.com/ikvm-revived/ikvm/blob/master/Directory.Build.props#L13). You would need to dig through the old `.build` files (which are no longer in use, but kept around from the old build process to troubleshoot issues like these) to work out which parts we are missing to successfully build on .NET Framework.

I edit openjdk.targets The targets file is as follows and can be generated Assembly IKVM.OpenJDK.Core.dll,
A new exception occurred，Thanks 。

The security transparent method 'Java. Lang. processenvironment. Environmentblock()' failed to attempt to access the security critical method 'java_java_lang_processenvironment. Environmentblock()'.
The assembly "ikvm. Openjdk. Core, version = 8.5.0.3, culture = neutral, publickeytoken = 13235d27fcbfff58" is marked as allowpartiallytrustedcallersattribute and uses a level 2 security transparency model. By default, level 2 transparency will cause all methods in the allowpartiallytrustedcallers assembly to become security transparent, which may be the cause of this exception.

openjdk.targets  edit：
  <Target Name="AssemblyInfoJava">
    <PropertyGroup>
      <IKVMRuntime>IKVM.Runtime, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0</IKVMRuntime>
      <IKVMAWTWinForms>IKVM.AWT.WinForms, PublicKey=0024000004800000940000000602000000240000525341310004000001000100DD6B140E5209CAE3D1C710030021EF589D0F00D05ACA8771101A7E99E10EE063E66040DF96E6F842F717BFC5B62D2EC2B62CEB0282E4649790DACB424DB29B68ADC7EAEAB0356FCE04702379F84400B8427EDBB33DAB8720B9F16A42E2CDB87F885EF413DBC4229F2BD157C9B8DC2CD14866DEC5F31C764BFB9394CC3C60E6C0</IKVMAWTWinForms>
      <Copyright>Copyright</Copyright>
    </PropertyGroup>

**Comment by NightOwl888** [comment]
Thanks for the info.

I submitted #48 with that change, and also changed the `<LangVersion>` to 7.0, because [according to the docs CAS is not supported beyond C# 7.0](https://docs.microsoft.com/en-us/previous-versions/dotnet/framework/code-access-security/using-libraries-from-partially-trusted-code). It builds successfully, but since there are no tests on this project I haven't confirmed changing the language version fixes the CAS issue.

Could you provide a basic test for this, or at least the code to do the test? If you add a test project, please put it in a new  `tests` folder inside the repository root folder.

**Comment by CYDHJ** [comment]
Now it's still the same .
The security transparent method 'Java. Lang. processenvironment. Environmentblock()' failed to attempt to access the security critical method 'java_java_lang_processenvironment. Environmentblock()'.

code for tests :https://github.com/CYDHJ/tests

> Thanks for the info.
> 
> I submitted #48 with that change, and also changed the `<LangVersion>` to 7.0, because [according to the docs CAS is not supported beyond C# 7.0](https://docs.microsoft.com/en-us/previous-versions/dotnet/framework/code-access-security/using-libraries-from-partially-trusted-code). It builds successfully, but since there are no tests on this project I haven't confirmed changing the language version fixes the CAS issue.
> 
> Could you provide a basic test for this, or at least the code to do the test? If you add a test project, please put it in a new `tests` folder inside the repository root folder.

Now it's still the same .
The security transparent method 'Java. Lang. processenvironment. Environmentblock()' failed to attempt to access the security critical method 'java_java_lang_processenvironment. Environmentblock()'.

code for tests :https://github.com/CYDHJ/tests

**Comment by CYDHJ** [comment]
code for tests :https://github.com/CYDHJ/tests ，Please help me, thank you。

**Comment by NightOwl888** [comment]
Hi there. I removed partial trust support in #49, so this should no longer be an issue. It can be added back if someone needs it, but I haven't personally dealt with CAS for almost 2 decades and I suspect it isn't in wide use anymore, anyway.

Thanks for sending the test code. However, I wasn't able to use it because I don't know what command(s) you used to generate the files that were included. Could you provide that info as well?

**Comment by CYDHJ** [comment]
Thanks you.

first run command build.framework.cmd Build complete。

after run  [bulid_MQ.cmd](https://github.com/CYDHJ/tests/blob/main/bulid_MQ.cmd) 
command Build MQ-NEW.dll :
ikvmc -target:library -recurse:.\JAR\*.jar -version:2.0 -out:.\JAR\MQ-NEW.dll

**Comment by CYDHJ** [comment]
> Hi there. I removed partial trust support in #49, so this should no longer be an issue. It can be added back if someone needs it, but I haven't personally dealt with CAS for almost 2 decades and I suspect it isn't in wide use anymore, anyway.
> 
> Thanks for sending the test code. However, I wasn't able to use it because I don't know what command(s) you used to generate the files that were included. Could you provide that info as well?

Please help me, thank you。

**Comment by wasabii** [comment]
Whatever was going on here has got to have drastically changed with 8.2 Issue is pretty old. Request reporter to reopen if still a problem. And also to use the latest version.
