### ISSUE TITLE
Task: Convert usage from PassiveWeakDictionary<TKey, TValue> to ConditionalWeakTable<TKey, TValue>

### ISSUE THREAD

**Issue by NightOwl888** [ikvm-revived/ikvm#51]
In .NET 4.0+ there is now a [`ConditionalWeakTable<TKey, TValue>` class](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2?view=net-6.0) that ties directly into the GC in native code, which can be used as a direct replacement for `PassiveWeakDictionary<TKey, TValue>`.

It should be possible to use this as a drop-in replacement as it has the same constraints, same key comparison, and same APIs, except for it is lacking a `Dispose()` method and instead relies on a finalizer to clean up unmanaged resources.

**Comment by wasabii** [comment]
It looks safe to replace to me. It's used to associate TypeWrappers with ghost objects. No unmanaged resources involved.
