### ISSUE TITLE
JavaReference Design Proposal

### ISSUE THREAD

**Issue by wasabii** [ikvm-revived/ikvm#54]
It would be useful if users could include a `JavaReference` within their .NET projects to specify a path to a JAR file, and have this JAR file automatically included in their project.

We would build a NuGet package that distributes MSBuild targets that implement the `JavaReference` functionality.

The `JavaReference` tag would appear in MSBuild projects similar to the `Reference` attribute now.

```
<ItemGroup>
  <JaveReference Include=".\foo-lib.jar" />
</ItemGroup>
```

`JavaReference` would support both a path to a JAR file, as well as a path to the root of a classpath.

Additional metadata would be supported to specify properties of the generated assembly, such as it's name, version, and target framework. These properties would otherwise be determined automatically.

The MSBuild targets file would set up a ResolveJavaReferences target to execute before ResolveAssemblyReferences. This target would ensure that each referenced JAR file or classpath root was compiled when needed by IKVMC into an associated assembly. These assembly results should be cached somewhere, based on the identity of the JAR file. It is important that this cache be shared between projects, as you do not want multiple projects within the same solution to end up referencing a different generated assembly. I would suggest they end up cached in something like `~/.ikvm/cache/<identity>/assembly.dll`.

The notion of an "identity" is a hard one. Is it the name of the jar? Is it the name of the jar + the version of ikvmc that generated it? Is it the name of the generated assembly? Is it a hash of the jar? 

I suspect this proposal can actually be reused by the #50.

**Comment by NightOwl888** [comment]
After dealing with #50 somewhat, I can see that this is the more difficult of the 2 tasks. Processing the `<JavaReference>` elements is straightforward, but there will need to be some kind of manifests so we can tell what is a local and what is a remote reference. And there is a syntax in the XML that can be used to also add these local references (also [available on the command line](https://stackoverflow.com/a/42931883), but since we are outputting a new XML file each build, it would be easier just to write the XML appropriately).

As for repackaging in `NuGet`, we cannot rely on Maven because the `.jar` file is local (and presumably either checked into the repo, or set up to automatically download from a non-Maven URL if not available). So, there are basically 2 ways we can go:

1. Pack the `.jar` file in the `.nupkg` so projects that depend on us (and those that depend on those, reclusively) can rebuild it, similar to how we do it with `MavenReference`.
2. Pack the `.dll` files in the `.nupkg` for each target framework.

Option 2 is a bit problematic because we can end up with mismatching target frameworks, and NuGet enforces which TFM can depend on another TFM.

Also, strong naming may be an issue because we could end up with multiple `.dlls` with the same NuGet package ID and version, but are signed by different people. However, if we build from a `.jar` we can either use the `ikvm.snk` or the user can supply one.

**Comment by wasabii** [comment]
PR #82

**Comment by wasabii** [comment]
PR #82 has been merged. A prerelease is building with JavaReference support. I would appreciate people testing this out.

**Comment by wasabii** [comment]
So, design decision. Two parts.

First, I'm going to rename JavaReference to IkvmReference. Something about JavaReference wasn't sitting right with me. To me it seemed to have the unknown future potential to conflict with some other people's Java integration. Or maybe the future MS effort at the JVM bridge. I don't know. It seemed wrong. What we're doing here isn't just some reference to some JVM. It's recompiling Java code into .NET code. So, it feels different.

Second, it looks like somebody reserved the `IKVM.Sdk` package ID on nuget.org. That sucks. I don't know who. @NightOwl888  doesn't know who. I messaged support@nuget.org, and didn't hear back. Maybe never will. But, it made me reevaluate whether we even needed a separate package for this. Do we? I think not.

Who would even install the IKVM package on NuGet otherwise? You have to either download the tools drop, or install IKVM.Sdk along side it, to use it with static assemblies. Installing IKVM alone is useful if you want to load JARs dynamically, sure, and don't want any static compilation of anything. But let's face it: almost everybody is going to want static compilation and intellisense while developing. So, it makes sense to put those features into the main IKVM package. And also avoids us needing to solve the reserved package ID of IKVM.Sdk.

**Comment by wasabii** [comment]
Also, since this is now merged, I'm going to close this bug, after ending it with the relevant portion of the README.md about this feature:




## IkvmReference

> **Warning**
> IkvmReference fails to properly build assemblies under a TFM > `netcoreapp3.1`. Until this is resolved, you can use `netcoreapp3.1` to access the Java assembly in a library that you reference from other projects.

This project contains the build infrastructure required for referencing Java libraries from .NET projects.

Install the `IKVM` package in a project that wants to reference Java libraries. Use the `IkvmReference` `ItemGroup` to indicate which Java libraries your project references.

Example:

```
    <ItemGroup>
        <IkvmReference Include="..\..\ext\helloworld-2.0.jar" />
    </ItemGroup>
```

The output assembly will be generated as part of your project's build process. Additional metadata can be added to `IkvmReference` to customize the generated assembly.

+ `Identity`: The identity of the `IkvmReference` item can be either a) path to a JAR file b) path to a directory or c)
an otherwise unimportant name.
+ `AssemblyName`: By default the `AssemblyName` is generated using the rules defined by the `Automatic-Module-Name`
specification. To override this, do so here.
+ `AssemblyVersion`: By default the `AssemblyVersion` is generated using the rules defined by the `Automatic-Module-Name`
specification. To override this, do so here.  (not yet supported)
+ `Compile`: Optional semi-colon separated list of Java class path items to compile into the assembly. By default this
value is the `Identity` of the item, if the identity of the item is an existing JAR file or directory (not yet supported). MSBuild globs
are supported to reference multiple JAR or .class files.
+ `Sources`: Optional semi-colon separated list of Java source files to use during documentation generation. (not yet supported)
+ `References`: Optional semi-colon separated list of other `IkvmReference` identity values to specify as a reference
to the current one. For instance, if `foo.jar` depends on `bar.jar`, include both as `IkvmReference` items, but specify
the identity of `bar.jar` on the `References` metadata of `foo.jar`.
+ `Debug`: Optional boolean indicating whether to generate debug symbols (non-portable). By default this is determined
based on the overall setting of the project.
+ All other metadata supported on the `Reference` MSBuild item group definition.

`IkvmReference` is not transitive. Including it in one project, and adding a dependency to that project from a second
project, will not result in the same reference being available on the second project. Instead, add the reference to
each project.

For each project to resolve to the same resulting assembly, ensure their settings are identical.


```
    <ItemGroup>
        <IkvmReference Include="helloworld.jar">
            <AssemblyVersion>1.0.0.0</AssemblyVersion>
        </IkvmReference>
        <IkvmReference Include="helloworld-2.jar">
            <AssemblyName>helloworld-2</AssemblyName>
            <AssemblyVersion>2.0.0.0</AssemblyVersion>
            <References>helloworld.jar</References>
            <Aliases>helloworld2</Aliases>
        </IkvmReference>
    </ItemGroup>

```

**Comment by xiaochao00** [comment]
hi @wasabii, 

how does  `IkvmReference` uesed in Visual Studio? 

I can generate *.dll in a simple c# project, but it can`t build and generate dll in VS;
It seems VS can`t recognize the element `IkvmReference`;

Background:
I wan to generate *.dll by <third party>.jar, which dll will be used into unity;
I can generate this dll in my machine c# environment, but it can`t run well in unity environment;
So I want to use VS or Unity environment to generate *.dll by *.jar.

**Comment by NightOwl888** [comment]
Since IKVM only currently supports .NET Framework and .NET Core, there is no support for running on Unity. For that to work, there would either need to be a .NET Standard target or target unity explicitly, at minimum. There is likely a lot more to it than that, though. 

https://docs.unity3d.com/Manual/overview-of-dot-net-in-unity.html
