### ISSUE TITLE
Replace SharpZipLib with System.IO.Compression

### ISSUE THREAD

**Issue by wasabii** [ikvm-revived/ikvm#62]
Should be a pretty easy change. Reducing one more dependency. I'd imagine System.IO.Compression didn't exist at the time.

**Comment by NightOwl888** [comment]
I don't believe that System.IO.Compression supports BZip2 format. There may be some Java components that use it. We may be able to reduce the need for SharpZipLib, but not totally eliminate it.

**Comment by wasabii** [comment]
Pretty sure Java doesn't support BZip2 either. The JAR format was based on a 1998 version of the PKZip standard.

And a quick check on java.util.packaging confirms no classes to handle BZip2.

**Comment by wasabii** [comment]
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/zip/package-summary.html

**Comment by NightOwl888** [comment]
I can confirm that lucene benchmark is using https://commons.apache.org/proper/commons-compress/ to do the BZip2 compression, not the JDK.

**Comment by NightOwl888** [comment]
I thought this would be easier than it actually is.

SharpZipLib's version of `ZipFile` supports a comment at the beginning of the file and on each entry, but `System.IO.Compression` has no such functionality. IKVM uses the comment field in a few places and `SharpZipLib` reads it from the underlying stream when opening either a `ZipFile` or getting one of its entries.

- https://github.com/ikvm-revived/ikvm/blob/7325bb029d0823687ef6ce010abbcb923ad7d799/ikvmc/IkvmcCompiler.cs#L1272-L1276
- https://github.com/ikvm-revived/ikvm/blob/7325bb029d0823687ef6ce010abbcb923ad7d799/ikvmc/IKVM/Internal/CompilerClassLoader.cs#L749-L750
- https://github.com/ikvm-revived/ikvm/blob/7325bb029d0823687ef6ce010abbcb923ad7d799/ikvmc/IKVM/Internal/CompilerClassLoader.cs#L3332-L3349
- https://github.com/ikvm-revived/ikvm/blob/7325bb029d0823687ef6ce010abbcb923ad7d799/ikvmc/IKVM/Internal/CompilerClassLoader.cs#L3404-L3415
- https://github.com/ikvm-revived/ikvm/blob/7325bb029d0823687ef6ce010abbcb923ad7d799/ikvmc/IKVM/Internal/CompilerClassLoader.cs#L3550-L3577

I started digging under the hood to see if I could implement this somehow on top of `System.IO.Compression.ZipArchive`, but the only way to read the comment data appears to be to use the stream directly. And there is some weird special case codepage logic for certain platforms in `SharpZipLib` in which the comments are written. To read the comment on each entry, the difference between what constitutes an "entry" and a "comment" would somehow need to be detected. I think it could be done, but I don't think the effort is worth removing a small dependency.

![image](https://user-images.githubusercontent.com/1538288/171075684-10df75da-81c3-40d8-b857-14843196bb86.png)

I am not sure how critical the comment functionality is. As you see above, 2 of the 3 places that call `CompilerClassLoader.CreateJar()` don't set a comment however, the other case passes it from a file being read to a virtual file that is being written.

**Comment by wasabii** [comment]
Why do you need the comments section?

**Comment by NightOwl888** [comment]
I don't know specifically whether it is required by IKVM or not. All I know is that it reads and passes the comments through to the compressed output from any `.zip` file that it reads. And it will include an extra zip entry in the output for a non-empty comment that doesn't include data, which may make reading by `System.IO.Compression` incompatible in those cases.

**Comment by wasabii** [comment]
Then the thing to do would be to understand what the comments are used for, and whether they are just decorations, or functional.

**Comment by bogatykh** [comment]
JAR file comments are non functional, they are just comments. For example, Java obfuscators write information about obfuscation tool. IKVM writes Exporter tool version in IkvmExporterInternal.GetVersionAndCopyrightInfo.

In my opionon comment writing can be omitted in favor to removing SharpZipLib dependency.
