### ISSUE TITLE
IKVM EventHandler cannot be converted to RoutedEventHandler

### ISSUE THREAD

**Issue by jz499** [ikvm-revived/ikvm#7]
I'm trying to execute a function/method when a button is clicked, However I'm getting Javac errors.
Does any know the correct code to use for a button click event?

Description:
-------------
Using IKVM to call .net UI components (buttons, textboxes,etc..) from java.

Code:
-------
button.add_Click(new cli.System.EventHandler(
new cli.System.EventHandler.Method () {
public void Invoke (Object sender, cli.System.EventArgs e) {
this.bu_click(sender, e);
}
}));

void bu_click(Object sender, cli.System.EventArgs e)
{
System.out.println("success");
}

void bu_click(Object sender, cli.System.EventArgs e)
{
System.out.println("success");
}

Error message:
-----------------
App1.java:130: error: method add_Click in class ButtonBase cannot be applied to given types;
button.add_Click(new cli.System.EventHandler(
^
required: RoutedEventHandler
found: EventHandler
reason: argument mismatch; EventHandler cannot be converted to RoutedEventHandler

**Comment by ams-tschoening** [comment]
Just try again with a `RoutedEventHandler`, just like the error message says. I doubt that this has to do with IKVMC, but you seem to simply create the wrong instances.

https://docs.microsoft.com/de-de/dotnet/api/system.windows.routedeventhandler?view=netcore-3.0

**Comment by jz499** [comment]
Thanks for the feedback ams,
Yes I know it's not an IKVM issue, I'm trying to execute a function when a button is clicked.
I can't figure out how this is done from Java using IKVM (cli.System.Windows)

**Comment by ams-tschoening** [comment]
That doesn't answer if you simply tried with a `RoutedEventHandler` instead, pretty much like what the error message is telling you.

**Comment by jz499** [comment]
As per IKVM, the RouteEventHandler should look like the following:

win_max.add_Click(new RoutedEventHandler(myhandler()));

}
	 new Application().Run(mywin);
}
    
static cli.System.Windows.RoutedEventHandler.Method myhandler() 
{
	tbox_main.AddText("Hello World" );
}

I get errors when compiling, cli.System.Windows.RoutedEventHandler.Method myhandler()
requires a return type and doesn't accept type VOID. Could this be an issue with IKVM?
It seems as though IKVM doesn't support delegates, the sample code above should work.

**Comment by ams-tschoening** [comment]
Where exactly do you get the signature of your `RoutedEventHandler` from? It looks different than what I provided with the link above:

https://docs.microsoft.com/de-de/dotnet/api/system.windows.routedeventhandler?view=netcore-3.0

I don't understand your call of `myhandler()` as well, as it doesn't return anything and doesn't look like a callback or lambda or some code executed later. Is `public static void cli.[...]` even valid Java?

Looking at your first comment, if I was you, I would have simply started replacing `new cli.System.EventHandler(` with `new cli.System.RoutedEventHandler(` and kept everything else the same. Or is this a different problem than before now?

**Comment by jz499** [comment]
Exactly, it is different.
This could be an ikvm mapping issue. When I call the RoutedEventHandler class from java, this is the syntax that's displayed --> "cli.System.Windows.RoutedEventHandler.RoutedEventHandler(Method, arg0)"

**Comment by ams-tschoening** [comment]
> cli.System.Windows.RoutedEventHandler.RoutedEventHandler(Method, arg0)

But that's not what you are invoking in your example, you only provide one argument, so are calling the wrong CTOR already. From my understanding, `myhandler` is not a callback of any kind, it's a function call returning nothing in the end. Additionally, that function definition doesn't look like valid Java at all to me.

Isn't `Method` in your provided signature simply the the following? If so, you would need to get a reference to some method using reflection and provide that.

https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Method.html

I don't even understand how you are coming from your first comment to the last ones. I strongly suggest to simply start again at your first comment and do what the error message says: Replace `EventHandler` with `RoutedEventHandler`.

Additionally, you should format your provided code better readable and provide the exact error messages you get. `null` for example is not a return type or something like that and it can't be returned in functions with return type `void`. Of course there might be some problem in IKVM, but it's simply difficult to follow your descriptions currently.

**Comment by jz499** [comment]
I agree ams, I did not implement the RoutedEventhandler correctly(coding between java and .net is sometimes confusing). I made some changes to the code after reviewing the oracle doc and came up with the following:

apps1 obj = new apps1();
Class cls = obj.getClass();
win_max.add_Click(new RoutedEventHandler(cli.System.EventHandler.Method.class.getDeclaredMethod("mymethod", cls), null));
}
static void mymethod()
{
tbox_main.AddText("Hello World" );
}


However; I get the following when compiling:

Exception in thread "main" java.lang.NoSuchMethodException: cli.System.EventHandler$Method.mymethod(apps1)
        at java.lang.Class.getDeclaredMethod(Class.java:2164)
        at apps1.main(App1.java:69)

I'm not clear why I get a NosuchMethodException.

**Comment by ams-tschoening** [comment]
You are searching the wrong class for `mymethod`. If at all it's part of your own class, so you need something like `cls.getDeclaredMethod("mymethod", null)`.

**Comment by jz499** [comment]
Hi ams; still getting the same error, here's the modified code:

Class<apps1> cls = apps1.class;
win_max.add_Click(new RoutedEventHandler(cls.getDeclaredMethod("mymethod", cls), null));
}
static void mymethod()
{
tbox_main.AddText("Hello World" );
}

Error:
Exception in thread "main" java.lang.NoSuchMethodException: apps1.mymethod(apps1)
at java.lang.Class.getDeclaredMethod(Class.java:2164)
at apps1.main(App1.java:70)

**Comment by jz499** [comment]
Here's another syntax options, with this one I get a NUllPointer Exception:
win_max.add_Click(new RoutedEventHandler(cls.getDeclaredMethod("mymethod"), null));

error:
Exception in thread "main" java.lang.NullPointerException
 at cli.System.Delegate.DelegateConstruct(Unknown Source)
 at apps1.main(App1.java:70)

**Comment by ams-tschoening** [comment]
The last call at least makes somewhat sense, but I can't tell you if that is correct at all or how IKVM implements the delegate-thing you need. I suggest looking at `cli.System.Delegate.DelegateConstruct` what the source of the NPE might be. It might be as simple as that providing the additional `null` as arguments is not allowed.

But I really can't you help any further with this, you need to debug this on your own. I have no idea how these things are supposed to work as well and no time to dig any deeper.

**Comment by jz499** [comment]
Thanks arms-tschoening, really appreciated all of your feedback. I'll close this case permanent.
