### ISSUE TITLE
System.IO.FileNotFoundException: netstandard in ikvmc execution

### ISSUE THREAD

**Issue by gglyggly** [ikvm-revived/ikvm#74]
Hi

Tool version: [IKVM-8.2.0-prerelease.809-tools](https://github.com/ikvm-revived/ikvm/releases/download/8.2.0-prerelease.809/IKVM-8.2.0-prerelease.809-tools-netcoreapp3.1-win7-x64.zip)

I used the ikvmc tool to convert jar to dll as the framework version, with below issue:

> C:\Downloads\IKVM-8.2.0-prerelease.809-tools-netcoreapp3.1-win7-x64>ikvmc -out:lm.dll lm.jar
> IKVM.NET Compiler (8.2.0-prerelease.809)
> Copyright c 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug
> 
> *** INTERNAL COMPILER ERROR ***
> 
> PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE
> 
> ikvmc, Version=8.2.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
> C:\Downloads\IKVM-8.2.0-prerelease.809-tools-netcoreapp3.1-win7-x64
> 3.1.25 64-bit
> 
> System.IO.FileNotFoundException: netstandard
> at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\a\ikvm\ikvm\IKVM.Reflection\Universe.cs:line 828
> at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList1 references, IList1 userLibPaths) in D:\a\ikvm\ikvm\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
> at ikvmc.IkvmcCompiler.Compile(String[] args) in D:\a\ikvm\ikvm\ikvmc\IkvmcCompiler.cs:line 178
> at ikvmc.IkvmcCompiler.Main(String[] args) in D:\a\ikvm\ikvm\ikvmc\IkvmcCompiler.cs:line 112

![image](https://user-images.githubusercontent.com/48202066/172372195-a1f8d72d-b423-420c-a9c4-73bed1eecd6b.png)

**Comment by NightOwl888** [comment]
I discovered the solution to this [here](https://github.com/ikvm-revived/ikvm/issues/45#issuecomment-1141977376).

To prevent it from searching for `netstandard.dll`, you must use the `-nostdlib` option and `-r:<ikvmtools>/refs/*.dll` or `-reference:<ikvmtools>/refs/*.dll`, where `<ikvmtools>` is the path to `ikvmc`.  This will build an assembly that targets `netcoreapp3.1` (which should also run on an app that targets `net5.0` or `net6.0`).

```console
ikvmc -out:log4j.dll F:\Users\shad\Downloads\log4j-core-2.17.2.jar -nostdlib -r:F:\Users\shad\Downloads\IKVM-8.2.0-prerelease.809-tools-netcoreapp3.1-win7-x64\refs\*.dll
```

**Comment by gglyggly** [comment]
Great, it worked, thanks so much!

**Comment by wasabii** [comment]
@gglyggly I hoped to let people try it out for a couple releases and expose the more obvious bugs before releasing. So I'd give it another 2 weeks minimum.

There are a few issues that I do think are blockers. The -nostdlib thing, I think, needs to be resolved first.

**Comment by Loffe** [comment]
I also ran into this problem, however adding `-nostdlib` did not solve the issue.

> I have previously used IKVM from Windward (version 8.5.0.2) and have a build script (in Gradle) calling `ikvmc.exe` directly. I prefer this approach since I want to understand the details of translating a java library to .NET.

Without `-stdlib` i get the same error:

```
IKVM.NET Compiler (8.2.1+Branch.main.Sha.e85684966cf595d7942d6930fda9c27d23b509e1)
Copyright c 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug


*** INTERNAL COMPILER ERROR ***

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

ikvmc, Version=8.2.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Users\eloffer\Downloads\IKVM-8.2.1-tools-ikvmc-netcoreapp3.1\win7-x64\
3.1.27 64-bit

System.IO.FileNotFoundException: netstandard
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in D:\a\ikvm\ikvm\src\IKVM.Reflection\Universe.cs:line 789
   at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in D:\a\ikvm\ikvm\src\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
   at ikvmc.IkvmcCompiler.Compile(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 178
   at ikvmc.IkvmcCompiler.Main(String[] args) in D:\a\ikvm\ikvm\src\ikvmc\IkvmcCompiler.cs:line 112
```

If I add `-nostdlib  -reference:C:/Users/eloffer/Downloads/IKVM-8.2.1-tools-ikvmc-netcoreapp3.1/win7-x64/refs/*.dll` I get a similar but not identical error:

```
IKVM.NET Compiler (8.2.1+Branch.main.Sha.e85684966cf595d7942d6930fda9c27d23b509e1)
Copyright c 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

Error: unable to find 'netstandard.dll'.
```

Any idea what I am missing?

**Comment by wasabii** [comment]
You need to add each reference assembly with a -reference option.

**Comment by Loffe** [comment]
Ah, I see. I was under the impression that globbing was supported, both by the comment above mentioning `-reference:<ikvmtools>/refs/*.dll` and also in https://github.com/ikvm-revived/ikvm/issues/45#issuecomment-1141977376.

Manually expanding the list of all reference dll:s (and using a response file with all arguments) got it working 😃 👍

**Comment by rayanngage2** [comment]
> 

can I ask what did you do to got it working

I can't repaire it
D:\jarpack>ikvmc -out:bcp-sdk-1.0.0.RELEASE.dll bcp-sdk-1.0.0.RELEASE.jar -nostdlib -r:*.dll
ikvmc (8.4.4+Branch.main.Sha.103f78408061ddcb58e3a5715ff02893ca0216b2)
Copyright ? 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

Error: unable to find 'netstandard.dll'.

**Comment by GeorgeS2019** [comment]
@NightOwl888 

> https://github.com/ikvm-revived/ikvm/issues/45#issuecomment-1141977376
I have the same problem today After this approach fail

```
<ItemGroup>
  <IkvmReference Include="..\..\ext\helloworld-2.0.jar" />
</ItemGroup>
```

**Comment by google-mirror** [comment]
> > 
> 
> can I ask what did you do to got it working
> 
> I can't repaire it D:\jarpack>ikvmc -out:bcp-sdk-1.0.0.RELEASE.dll bcp-sdk-1.0.0.RELEASE.jar -nostdlib -r:*.dll ikvmc (8.4.4+Branch.main.Sha.103f78408061ddcb58e3a5715ff02893ca0216b2) Copyright ? 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug
> 
> Error: unable to find 'netstandard.dll'.

the same error
