### ISSUE TITLE
NuGet Repository?

### ISSUE THREAD

**Issue by mbinsfeld** [ikvm-revived/ikvm#8]
At Windward we've been publish builds of IKVM to our NuGet repository [here](https://www.nuget.org/packages/IKVM.WINDWARD/). Should we create a NuGet repository for ikvm-revived to publish future versions to?

**Comment by ams-tschoening** [comment]
That heavily depends on if IKVM gets somewhat successfully revived here or not I guess. :-) If it does, we should. Can that be decided right now? In my opinion: No.

Is there are concrete reason you want to create such a repo right now or are you only thinking in general about it? Sounds to me right now that two repos would needed to be kept in sync for no real benefit.

**Comment by ams-tschoening** [comment]
@DavidThi808 

> In addition we need to get it up on NuGet. At present the only IKVM on NuGet is the original, one by qCat, and Windward's. What/how do you propose doing this as well as keeping the private signing key confidential?

https://github.com/wwrd/ikvm8/issues/3#issuecomment-588337872

I have absolutely no idea and experience with NuGet, so why not simply keep publishing as Windward for the time being?

**Comment by DavidThi808** [comment]
We have a critical interest in keeping IKVM alive and rock solid. Because of the siging & NuGet issues, I think we need to stick with our project. It's not secure to push up code and sign it under Windward's name when it's an open source project we don't control.

I'll get your .net core changes added to our project and you are welcome to work from it ongoing.

thanks - dave

**Comment by ams-tschoening** [comment]
> It's not secure to push up code and sign it under Windward's name when it's an open source project we don't control.

My suggestion was that you create a fork of the repo in `ikvm-revived` and sign/publish based on that. You do have full control over that fork and can decide on your own which parts of `ikvm-revived` you merge when. The benefit would be that we can link all devs of interest to `ikvm-revived` and hopefully get a new functional community at some point.

**Comment by DavidThi808** [comment]
> The benefit would be that we can link all devs of interest to ikvm-revived and hopefully get a new functional community at some point.
I think we already have a community around the Windward repo. It's got over 3K installs. And I think commercial users will prefer the processes we put in place around it.

**Comment by NightOwl888** [comment]
> It's not secure to push up code and sign it under Windward's name when it's an open source project we don't control.

Typically, OSS projects use their own signing key, not one that a company owns, and the `.snk` file is added to the public repo. This allows *anyone* to be able make a build. It reduces the barrier to entry to be able to contribute to the project.

Another option is to open source the code with no `.snk` file, and add an option to pass in parameters to enable signing that are disabled by default (so anyone can still build and contribute). Then you can have a privately controlled build pipeline (pulling the key from a secure vault) that does the signing whenever you roll a release. Of course, you don't necessarily need to own the repo for that to happen.

**Comment by DavidThi808** [comment]
@NightOwl888 @timotei @ams-tschoening 
I'd prefer that we all work together on a single repository. So how about I list out what I think we need from our requirements? And I think most (all?) commercial projects that use IKVM will support these requirements.

First we keep the .snk file confidential (we put it in the parent directory of the project and refer to it there in the build files, but that way it is not checked in). There are just 2 or 3 of us that have it.

Second no pull request gets pushed to master without one of the key people, who is not on the team that made the changes, approving it. In other words, if Matt here at Windward creates a PR, I can't approve it.

Third, we push each new official build up to NuGet so it's easily available to everyone using it.

Fourth, the only changes we make to master are bug fixes and getting it working on .Net Core. While we're good with .Net Core 3.1, I'm willing to aim for .Net Core 2.0 to support a wider number of users.

Does this make sense? Are you all up for this?

thanks - dave

**Comment by NightOwl888** [comment]
> I'd prefer that we all work together on a single repository.

Agreed.

> First we keep the .snk file confidential (we put it in the parent directory of the project and refer to it there in the build files, but that way it is not checked in). There are just 2 or 3 of us that have it.

Again, as long as the *default build* is setup so anyone who cares to contribute can run a build without the `.snk`, I don't see that as an issue.

> Second no pull request gets pushed to master without one of the key people, who is not on the team that made the changes, approving it. In other words, if Matt here at Windward creates a PR, I can't approve it.

Basically, 2 ways to go here

1. Don't allow anyone permission to push to the repo except those who can approve (everyone else must submit a PR).
2. Any other approach should have a clearly written policy in (or linked from) a `CONTRIBUTING.txt` or `CONTRIBUTING.md` file.

Making everyone submit PRs may be a good way to make sure all changes are peer reviewed before making it into master.

> Third, we push each new official build up to NuGet so it's easily available to everyone using it.

Hopefully, after the changes have been tested :).

> Fourth, the only changes we make to master are bug fixes and getting it working on .Net Core. While we're good with .Net Core 3.1, I'm willing to aim for .Net Core 2.0 to support a wider number of users.

IMO, to satisfy everyone, it should go something like:

1. From the current wwrd/ikvm8 master branch, [rebase on top of](https://stackoverflow.com/q/40009820) ikvm-revived. This will preserve the entire commit history and add all changes from wwrd to the end.
2. Make the necessary changes to support .NET Standard 2.0, which will support modern versions of virtually every platform in the .NET ecosystem. Targeting additional runtimes (such as .NET Core 3.1 directly) is an option, but do note this only makes sense if there are specific APIs in those runtimes that would help improve performance or compatibility. Single-targeting is a bit easier to maintain.
3. Makes no difference to me which repo the changes end up in (as long as it is OSS on GitHub), but step 1 ensures they can be merged either in ikvm-revived, in wwrd, or put into a new repo.

Careful not to confuse .NET Core 2.0 (which is a legacy runtime) with .NET Standard 2.0 (which is for creating portable libraries).  .NET Standard 2.0 is the most recent portable library target that still supports .NET Framework.

Take a look at [the most popular projects on NuGet.org](https://www.nuget.org/packages). With only a few exceptions, all of them support .NET Standard 2.0. In most cases, if .NET Standard 2.0 is not supported, .NET Standard 1.x is.

**Comment by ams-tschoening** [comment]
> From the current wwrd/ikvm8 master branch, rebase on top of ikvm-revived. This will preserve the entire commit history and add all changes from wwrd to the end.

Keep [wwrd_fork](https://github.com/ikvm-revived/ikvm/commits/wwrd_fork) in mind, that should contain all wwrd-commits already and might be handled during such a process as well somehow.

**Comment by DavidThi808** [comment]
@NightOwl888 Agree it's .NET Standard 2.0 (not .NET Core). I scramble those two at times.

@ams-tschoening What is the best way to get master it to match the Windward version? Is it just merge wwrd_fork? If so, how about you create a PR and then I'll verify it matches what we have and approve?

**Comment by DavidThi808** [comment]
@ams-tschoening Also, please add the following people to this project (full rights)
@igorkwwrd - he'll be working on this a lot with me.
@jimcwindward, @mbinsfeld, & @connorshore

**Comment by ams-tschoening** [comment]
@DavidThi808 Invites are out, not sure if I understood the request for the PR properly, but I did something: https://github.com/ikvm-revived/ikvm/pull/12

**Comment by timotei** [comment]
👍

**Comment by chacham2** [comment]
This thread seems to have deviated from the first post, leaving me slightly confused. :) Forgive me for asking: If i want to use NuGet, the appropriate package is IKVM.WINDWARD?

**Comment by royalstream** [comment]
> This thread seems to have deviated from the first post, leaving me slightly confused. :) Forgive me for asking: If i want to use NuGet, the appropriate package is IKVM.WINDWARD?

That's the one I'm referencing on my app and the version is what I would expect (8.5).
That said, I have no idea what the next step would be.
All the documentation I've found for IKVM is about running **ikvm** or **ikvmc** to run or compile jars, how is this supposed to work when you're referencing IKVM as a Library?

**Comment by igorkwwrd** [comment]
@royalstream I don't quite understand what do you mean by "use it as a library".
IKVM is a compiler that compiles Java byte-code into .NET IL. It takes .jar and .class files as the input and produces a .NET .dll or .exe as the output. Then you execute .exe or use .dll as any other .NET assembly.

**Comment by igorkwwrd** [comment]
The .dll produced by IKVM depends on IKVM assemblies, i.e. IKVM.*.dll
So, in your project you have to reference IKVM.WINDWARD package as well as the assembly you have compiled using ikvmc compiler.

**Comment by royalstream** [comment]
> @royalstream I don't quite understand what do you mean by "use it as a library".
> IKVM is a compiler that compiles Java byte-code into .NET IL. It takes .jar and .class files as the input and produces a .NET .dll or .exe as the output. Then you execute .exe or use .dll as any other .NET assembly.

That's exactly what I thought, so I didn't understand what the KVM.WINDWARD package was for.
Your second post answers that question: the output DLLs are not self-contained and you need to reference the IKVM library as well. Thanks.

**Comment by chacham2** [comment]
@royalstream The windward package is used for .NET to call the compiled library. It is added via Nuget and supplies the java runtime. Without it, for example, i get a bunch of BC30652 errors, Reference required to assembly 'IKVM.OpenJDK.Core, Version=8.5.0.2

**Comment by NightOwl888** [comment]
We now have a prerelease of this repository on NuGet: https://github.com/ikvm-revived/ikvm/issues/15
