### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Draspax** [ikvm-revived/ikvm#9]
Would it be possible to get a new release from this branch. One that includes ikvmc in a binaries zip. We would need clients to be able to download this for use with our application.

**Comment by ams-tschoening** [comment]
I don't have any such plans myself, so if things are urgent for you, I would suggest doing it on your own. Additionally I have some organisation with additional things around IKVM which might(!) contain what you are interested in as well:

https://github.com/ams-ts-ikvm
https://github.com/ams-ts-ikvm/ikvm-bin

Especially the latter has multiple different branches you might be interested in, some of those containing things I had built for my own use already. Wasn't sure yet if things are worth it moving over to ikvm-revived.

**Comment by ams-tschoening** [comment]
Closing here for now, because things simply don't have changed from my last answer. Feel free to reopen if necessary.
