### ISSUE TITLE
Conver jar to dll missing class

### ISSUE THREAD

**Issue by hung-hust-97** [ikvm-revived/ikvm#99]
I used version 8.2.0 to convert the file jar to dll but, I received an error in the image below, then, I used version 7.1, and it ran, but the DLL was missing the class PassportSevice that contains in the jar. This is the link jar: https://drive.google.com/file/d/1pvxC01o4bSjvjYqJRdg6LHAnx4wjCiqP/view?usp=sharing
![image](https://user-images.githubusercontent.com/32328578/178118527-5892e6f2-2789-41f1-ba29-5e415c822ca1.png)
Thanks very much

**Comment by wasabii** [comment]
It looks like you haven't specified any -reference items, nor the path to the IKVM.Runtime assembly to use with -runtime.
